// AUTO-GENERATED by scripts/stamp-build.mjs — do not edit by hand.
// Holds the git commit this osint-agent build was stamped from, surfaced at
// /health (`build`) so a deployed function can be checked against source.
export const BUILD_MARKER = "f88e17a";
export const BUILD_COMMITTED_AT = "2026-07-08T12:03:01+00:00";
