// AUTO-GENERATED by scripts/stamp-build.mjs — do not edit by hand.
// Holds the git commit this osint-agent build was stamped from, surfaced at
// /health (`build`) so a deployed function can be checked against source.
export const BUILD_MARKER = "e10fb57";
export const BUILD_COMMITTED_AT = "2026-07-05T04:34:08-07:00";
