// AUTO-GENERATED by scripts/stamp-build.mjs — do not edit by hand.
// Holds the git commit this osint-agent build was stamped from, surfaced at
// /health (`build`) so a deployed function can be checked against source.
export const BUILD_MARKER = "6ac45b6";
export const BUILD_COMMITTED_AT = "2026-07-01T05:17:13-07:00";
