/**
 * catalog.ts — Tool catalog, fan-out recipes, catalog cache, and finding labels.
 * Extracted from index.ts (lines 1299–1427).
 * Returned by the `list_tools` meta-tool. Lifted OUT of the system prompt so
 * the prompt stays small. The model calls list_tools at most once per
 * investigation (cached in CATALOG_CACHE keyed by investigation_id).
 */

export type CatalogEntry = { name: string; description: string; when_to_use: string; input: string };

export const TOOL_CATALOG: { tools: CatalogEntry[]; fan_outs: Record<string, string[]>; notes: string } = {
  tools: [
    { name: "gravatar_profile", description: "Gravatar lookup — confirms a real avatar/profile linked to an email.", when_to_use: "Cheap Stage-1 signal for emails. Auto-fired by triage_seed.", input: "{ email: string }" },
    { name: "rapidapi_breach_search", description: "PRIMARY breach source — RapidAPI Email Breach Search (~8000 lookups/month). For an email, returns the breach corpus it appears in: per-breach id/name, breach date, and the exposed field set with `sensitive` flags. A hit is an EXPOSURE association, not confirmed identity.", when_to_use: "FIRST breach lookup on every email seed. Corroborate hits with breach_check / leakcheck_lookup / hibp_lookup (independent corpora). Requires RAPIDAPI_KEY; self-skips if absent — fall back to breach_check.", input: "{ email: string }" },
    { name: "breach_check",   description: "Strong breach source — stolen.tax (1000 calls/day). Queries OsintCat database-search (email+password combos), Snusbase (identity records: name/phone/address/DOB), and OsintCat breach. Returns combined hit count plus per-source samples.", when_to_use: "Run alongside / as corroboration for rapidapi_breach_search on email seeds, and as the primary breach lookup when RAPIDAPI_KEY is not configured. Also accepts usernames via `value`. Do NOT auto-expand single-source weak leads or collisions with it.", input: "{ email?: string, value?: string }" },
    { name: "rapidapi_all_breaches", description: "RapidAPI Email Breach Search — All Breaches catalog. Reference list of the entire DataBreach.com corpus (per-breach name, id, row count, exposed field types, dates, summary, hibp_id). No PII / not email-specific.", when_to_use: "Only to contextualize a breach id surfaced by rapidapi_breach_search (corpus size, exposed fields) or to check whether a named breach is in the database. Optional `filter` substring. Not a per-subject lookup.", input: "{ filter?: string, limit?: number }" },
    { name: "leakcheck_lookup", description: "SECONDARY breach source — LeakCheck Pro v2 (200 calls/day). Returns leak sources, breach dates, and where present passwords/usernames for an email, username, or phone.", when_to_use: "Corroborate breach_check on confirmed emails and high-value handles. Especially valuable when breach_check returns 0 hits or thin data, or you want password/source detail. Do not spam on weak handles — 200/day budget.", input: "{ value: string, type?: 'auto'|'email'|'username'|'phone'|'hash'|'domain' }" },
    { name: "hibp_lookup", description: "Have I Been Pwned v3 — Troy Hunt's authoritative breach + paste corpus. Returns breach metadata (name, domain, date, data classes) for an email. Rate: 1 req/1.5s.", when_to_use: "Corroborate breach_check + leakcheck_lookup on every CONFIRMED email seed. Skip on speculative addresses.", input: "{ email, include_pastes?, truncate? }" },
    { name: "bosint_email_lookup", description: "OSINTNova (Bosint) email exposure check — surface-level breach + exposure indicators. 1000/day OSINTNova quota.", when_to_use: "Use once per justified email seed or confirmed follow-on email when it adds corroboration value.", input: "{ email }" },
    { name: "osint_navigator_query", description: "OSINT Navigator (navigator.indicator.media) — natural-language tool recommendation. Returns curated, verified OSINT tools (name + URL) for the asked workflow. Use to discover the right third-party tool to suggest to the user; do NOT invent tools.", when_to_use: "When the user asks for tool recommendations, or when planning a pivot you don't already have a wired tool for and want to point the user at a vetted external tool.", input: "{ query: string, skip_cache?: boolean }" },
    { name: "osint_navigator_search", description: "OSINT Navigator direct keyword/category tool-database search. Categories: domains_websites, social_media, image_video_analysis, geolocation_mapping, transport, companies.", when_to_use: "Browsing alternatives or when you already know the category. Pair with osint_navigator_query for natural-language follow-ups.", input: "{ query: string, category?: string, limit?: number }" },
     { name: "oathnet_lookup", description: "Leaked-data + identity source. v2 breach search for email/username/phone/domain/NAME; geo+ASN for ip. Shares a 500/day POOLED quota with all oathnet_* tools. type:'name' searches a person's full name as a free-text breach query. Optional dbnames[]/filter_id scope the corpus.", when_to_use: "A first-class breach source — run it as part of the mandatory opening breach sweep on the seed (including a NAME seed via type:'name') and on high-value selectors discovered mid-run. Name-only hits carry same-name collision risk → label them [VERIFY]/excluded_collision until a selector overlaps, but that is a LABELING rule, not a reason to skip the call.", input: "{ type: 'email'|'username'|'phone'|'domain'|'ip'|'name', value: string, dbnames?: string[], filter_id?: string }" },
     { name: "oathnet_stealer_search", description: "OathNet v2 STEALER-LOG credential search — highest-value infostealer surface. Returns credential records (log id, captured domain/subdomain/path/url, username, email, dates); raw passwords/cookies are REDACTED (you get a credential_present boolean). Shared 500/day pool.", when_to_use: "On any email/username/domain/ip/discord_id worth a stealer check. Set has_log_id=true to keep only rows that pivot into a victim log, then use oathnet_victims_search / oathnet_victim_manifest. Hits are [VERIFY] leads.", input: "{ value: string, has_log_id?: boolean, domains?: string[], filter_id?: string }" },
     { name: "oathnet_victims_search", description: "OathNet v2 VICTIM search — compromised hosts tied to a selector, keyed by log_id (device usernames, HWIDs, device IPs/emails, linked discord_ids, doc counts). No raw creds. Shared 500/day pool.", when_to_use: "To find infected-host manifests for an email/username/ip/discord_id, or after a stealer hit that carried a log_id. Pivot a log_id into oathnet_victim_manifest. Label device identifiers [VERIFY].", input: "{ value: string, total_docs_min?: number, filter_id?: string }" },
     { name: "oathnet_victim_manifest", description: "OathNet v2 — one victim log's MANIFEST (file tree: names/types/sizes only, NO contents). Shared 500/day pool.", when_to_use: "After selecting a log_id from oathnet_victims_search / oathnet_stealer_search, to see which files exist before reading one via oathnet_victim_file.", input: "{ log_id: string }" },
     { name: "oathnet_victim_file", description: "OathNet v2 — read ONE victim file, returned REDACTED: metadata (size, line count, SHA-256) + a masked preview with passwords/cookies/tokens stripped. Raw credentials are never returned. Shared 500/day pool.", when_to_use: "For triage of a specific manifest file (wallet/session/keepass presence), NOT to harvest secrets. Pass log_id + file_id from the manifest.", input: "{ log_id: string, file_id: string }" },
     { name: "oathnet_victim_archive", description: "OathNet v2 — REFERENCE the full victim-log ZIP. MANUAL-CONSENT ONLY: never downloads bytes into the investigation; returns the authenticated endpoint for out-of-band operator retrieval. Refuses without confirm:true.", when_to_use: "Only when the user EXPLICITLY authorizes pulling a full log. Never autonomous. Store a reference + hash, never raw archive contents.", input: "{ log_id: string, confirm?: boolean }" },
     { name: "oathnet_subdomains", description: "OathNet v2 — subdomains observed in stealer records for a domain (host list + count). Independent of crt.sh/hackertarget. Shared 500/day pool.", when_to_use: "On any domain seed/pivot, alongside crtsh_subdomains — overlap corroborates, unique hits add coverage.", input: "{ domain: string }" },
     { name: "oathnet_breach_dbnames", description: "OathNet v2 helper — autocomplete breach DATABASE names (name + record count + fields) for scoping. Cheap. Shared 500/day pool.", when_to_use: "Before a scoped breach query, to resolve a db-name fragment into exact names to pass as oathnet_lookup dbnames[].", input: "{ q: string }" },
     { name: "oathnet_ai_filter", description: "OathNet v2 — translate a natural-language breach query into a structured filter, returning a reusable filter_id to collapse multi-selector queries into fewer calls. Shared 500/day pool.", when_to_use: "When a breach/stealer/victim query is easier described in words than as params, or to reuse one filter across several searches. Pass the returned filter_id to oathnet_lookup / stealer / victims.", input: "{ query: string, index?: 'breach'|'stealer'|'victims' }" },
     { name: "oathnet_scanner", description: "OathNet SCANNERS — automated monitoring of newly-indexed breach/stealer data. action:'quota'/'list' are read-only; action:'create' sets up a PERSISTENT notifying monitor and requires confirm:true + explicit user authorization. Shared 500/day pool.", when_to_use: "Read quota/list freely. Only create a scanner when the user explicitly asks to monitor a subject over time — never autonomously.", input: "{ action: 'quota'|'list'|'create', name?, scanner_type?: 'breach'|'stealer', query?, notification_type?, confirm?: boolean }" },
    { name: "serus_darkweb_scan", description: "Serus darkweb exposure scan (api.serus.ai). One tool, seven identifier types: email, phone, username, domain, keyword, origin (IP/hostname), password. Initiates a scan and polls until completion (~5–30s). Returns breach count + breach names + data classes (masked by default; pass reveal:true to unmask passwords/tokens if the key has darkweb:reveal scope), paste count, and any extracted PII (emails, usernames, phones, names, crypto addresses). 0.25 credits per scan, 3 req/s write budget.", when_to_use: "SECONDARY / CORROBORATING breach source. Use only when the planner identifies independent-corpus value for a confirmed selector or contradiction. Use identifierType:'origin' for IP/hostname. Use identifierType:'password' only on confirmed seeds you own or are authorized to test. Pass reveal:true ONLY when the user explicitly authorizes unmasked breach data — it costs extra credits and is sensitive.", input: "{ identifierType: 'email'|'phone'|'username'|'domain'|'keyword'|'origin'|'password', identifierValue: string, reveal?: boolean }" },
    { name: "indicia_email", description: "Indicia (api.indicia.app) email intelligence — US person/broker + web-DB records linked to an email. Broker/breach-dump data.", when_to_use: "Corroborating source on a confirmed email seed alongside breach_check/leakcheck. Single hit is a LEAD, never confirmed alone. 1 token/call.", input: "{ query: string }" },
    { name: "indicia_phone", description: "Indicia phone intelligence — US person/broker + web-DB records linked to a phone number.", when_to_use: "Reverse-phone enrichment on a phone seed/selector. Corroborate before treating as identity. 1 token/call.", input: "{ query: string }" },
    { name: "indicia_person", description: "Indicia person search — US people-search/broker records for a full name, optionally narrowed by city + state.", when_to_use: "Part of the NAME/PERSON sweep for US subjects. Same-name collision risk → LEAD until a selector overlaps. 1 token/call.", input: "{ name: string, city?: string, state?: string }" },
    { name: "indicia_address", description: "Indicia address intelligence — individuals/records linked to a US street address.", when_to_use: "ADDRESS/PROPERTY cases to link residents/associates. Broker data → LEAD until corroborated. 1 token/call.", input: "{ address1: string, city?: string, state?: string, zip?: string }" },
    { name: "indicia_web_dbs", description: "Indicia web-DB breach aggregator — queries multiple breach corpora (leakcheck, snusbase, cloudsint, …) for a selector.", when_to_use: "Secondary/corroborating breach sweep on a confirmed selector. Never auto-pivot leaked passwords. 1-2 tokens/call.", input: "{ query: string, services?: string[] }" },
    { name: "indicia_hudsonrock", description: "Indicia Hudson Rock lookup — infostealer/compromised-machine credential exposure for an email, domain, or username. FREE.", when_to_use: "Cheap corroborating exposure check on emails/domains/usernames. Exposure is a LEAD. 0 tokens/call.", input: "{ query: string, type?: string }" },
    { name: "ipqualityscore_lookup", description: "IPQualityScore validity + fraud scoring (ipqualityscore.com). One tool, three identifier types: phone | email | ip. Returns valid flag + 0-100 fraud_score + type-specific signals (phone: active, line_type, carrier, CNAM name, recent_abuse; email: deliverability, disposable, leaked, names; ip: proxy/vpn/tor, bot_status, recent_abuse, connection_type). Free tier ~5000/mo.", when_to_use: "VALIDATION GATE — run EARLY on a phone/email/ip seed before spending on deep breach/people-search. If valid:false or fraud_score>=85, the identifier is reserved/fake/disposable: treat attributions to it as low-confidence and stop spending paid calls on it. Also a strong corroborator (carrier/line-type/name for phones; deliverability/leaked for emails; proxy/vpn for IPs).", input: "{ kind: 'phone'|'email'|'ip', value: string, country?: string }" },
    { name: "socialfetch_lookup", description: "PRIMARY profile fetch for tiktok/instagram/twitter/facebook handles + their content (10k credit pool). kind: profile | videos (tiktok) | posts (instagram) | tweets (twitter) | video (tiktok single).", when_to_use: "FIRST choice on corroborated handles or direct profile URLs for tiktok/instagram/twitter/facebook. Do not spray it across every platform for weak or colliding handles. For a blocked host (youtube/twitch/reddit/arbitrary page) use socialfetch_web_read instead; use jina_reader_scrape only for non-blocked hosts.", input: "{ platform, handle, kind? }" },
    { name: "socialfetch_web_read", description: "Read ANY web URL as clean markdown via SocialFetch's server-side fetch (/v1/web/markdown, ~1 credit/URL). Not origin-blocked the way r.jina.ai is.", when_to_use: "For a specific important URL on a host that jina_reader_scrape HARD-BLOCKS (youtube/youtu.be, x/twitter, twitch, reddit) or that Jina cannot reach. One URL at a time — never a bulk crawl; SocialFetch quota is low.", input: "{ url: string }" },
    { name: "socialfetch_whoami", description: "Validate the SocialFetch API key and return account info. FREE (zero credits).", when_to_use: "Optionally at session start to confirm the SocialFetch key is active before paid lookups.", input: "{}" },
    { name: "socialfetch_balance", description: "Return the current SocialFetch credit balance/status (healthy|grace|exhausted). FREE (zero credits).", when_to_use: "Before a batch of paid SocialFetch lookups, to confirm sufficient quota.", input: "{}" },
    { name: "cordcat_discord_lookup", description: "CordCat Discord OSINT — given a 17-20 digit Discord snowflake ID, returns Discord profile (username, global_name, avatar, banner, public_flags), breach hits, FiveM records, and DSA sanction statements.", when_to_use: "Every Discord snowflake ID surfaced as a seed or pivot. The Discord username alone is NOT enough — extract the numeric ID first (e.g. via jina_reader_scrape on a Discord profile/invite page). 60 req/hour budget.", input: "{ discord_id: string }" },
    { name: "jina_reader_scrape", description: "ONLY single-page scraper. Free Jina Reader returns clean LLM-ready markdown for any public URL.", when_to_use: "Default for a specific source page: profile pages, articles, forums, leak listings, dork hits, Discord/Telegram web links, and similar source material.", input: "{ url, maxChars? }" },
    { name: "exa_search", description: "Exa neural+keyword search with optional inline contents. Categories: company, research paper, news, pdf, github, tweet, personal site, linkedin profile, financial report. Date-bounded via startPublishedDate/endPublishedDate.", when_to_use: "PRIMARY semantic web search when it clearly adds value. Pair with minimax_web_search only when corroboration or broader coverage is justified.", input: "{ query, type?, numResults?, includeDomains?, excludeDomains?, startPublishedDate?, endPublishedDate?, category?, contents? }" },
    { name: "exa_find_similar", description: "Exa findSimilar — given a known URL, return semantically similar pages.", when_to_use: "After confirming any single profile URL (linkedin profile, personal site, github, twitter) — use to find the same person's other profiles or related entities. Powerful identity-pivot tool.", input: "{ url, numResults?, excludeSourceDomain?, contents? }" },
    { name: "exa_get_contents", description: "Exa /contents — fetch full text + AI summary + highlights for up to 10 URLs in one call. Best for bulk URL reading.", when_to_use: "When you have several URLs from exa_search / dorks and want their text in one batch instead of N jina_reader_scrape calls. Set livecrawl='always' for breaking news or pages you suspect Exa has cached stale.", input: "{ urls: string[], livecrawl?, text?, highlights?, summary?, maxCharacters? }" },
    { name: "ip_intel",       description: "IP geolocation, ASN, hosting info.", when_to_use: "Every ip seed and every IP discovered from DNS.", input: "{ ip: string }" },
    { name: "shodan_internetdb", description: "Open ports, vulns, cert subjects for an IP/domain via Shodan InternetDB.", when_to_use: "ip seeds and on resolved IPs of domain seeds.", input: "{ value }" },
    { name: "whois_lookup",   description: "RDAP/WHOIS registrant data for a domain.", when_to_use: "Every domain seed. Pivot on registrant email/name.", input: "{ domain }" },
    { name: "dns_records",    description: "A/AAAA/MX/NS/TXT/CNAME/SOA/CAA records + email-auth virtuals (SPF/DMARC/DKIM/BIMI, auto-translated to TXT).", when_to_use: "Every domain seed. Pivot on returned IPs and MX hostnames. For email-auth posture pass SPF/DMARC/DKIM (DKIM needs dkimSelector) — never query SPF as a real record type.", input: "{ host, types?: string[], dkimSelector? }" },
    { name: "crtsh_subdomains", description: "Certificate-transparency subdomain discovery.", when_to_use: "Every domain seed. Each subdomain → http_fingerprint.", input: "{ domain }" },
    { name: "hackertarget",   description: "Reverse-IP and hostsearch via hackertarget.com.", when_to_use: "domain (hostsearch) and ip (reverseiplookup) seeds.", input: "{ kind, value }" },
    { name: "username_sweep", description: "Built-in Username Sweep: parallel HTTP existence check across ~95 platforms for a handle. Edge-native. Only call this on a handle with NO spaces.", when_to_use: "Primary for direct username seeds. For name/person seeds, rank real-name search first and keep derived-handle results [VERIFY] until corroborated.", input: "{ username }" },
    { name: "username_search", description: "DEPRECATED alias of username_sweep, kept only for backwards compatibility.", when_to_use: "Do not call directly; prefer username_sweep. Never rank this alias ahead of real-name search for name/person seeds.", input: "{ username, platforms? }" },
    { name: "github_user",    description: "GitHub profile, public emails, repos, bio.", when_to_use: "Every username seed and on github.com hits from sweep.", input: "{ username }" },
    { name: "github_code_search", description: "Search public GitHub code for a string.", when_to_use: "Use for justified public-code context. Triage is advisory, not a prerequisite.", input: "{ query }" },
    { name: "hunter_domain_search", description: "Hunter.io domain search — emails associated with a domain plus department/seniority/sources.", when_to_use: "Every non-consumer domain seed and every domain pivoted from an email. Cheap and high-signal.", input: "{ domain, limit?, department?, seniority? }" },
    { name: "hunter_email_finder", description: "Hunter.io email finder — guess + verify an email from a person's name and a domain.", when_to_use: "When you have a name + corporate domain pair and want a likely email.", input: "{ domain, first_name?, last_name?, full_name? }" },
    { name: "hunter_email_verifier", description: "Hunter.io deliverability + risk verification for an email address.", when_to_use: "Run on any new high-value email to grade confidence (deliverable / risky / undeliverable, MX, SMTP, disposable, webmail).", input: "{ email }" },
    { name: "hunter_combined", description: "Hunter.io combined person + company enrichment for an email.", when_to_use: "Run on every confirmed email — returns name, role, social links, company info, employee count, tech stack.", input: "{ email }" },
    { name: "archive_url", description: "Submit a URL to the Wayback Machine to create a permanent archived snapshot (chain of custody).", when_to_use: "After confirming any evidence URL that may disappear (social posts, leak listings, scam sites). Required for [CONFIRMED] findings on volatile sources.", input: "{ url }" },
    { name: "hackernews_user",description: "Hacker News profile + recent comments.", when_to_use: "Every username seed.", input: "{ username }" },
    { name: "reddit_user",    description: "Reddit profile + recent activity.", when_to_use: "Every username seed.", input: "{ username }" },
    { name: "wayback_snapshots", description: "Wayback Machine snapshot index for a URL.", when_to_use: "url seeds. Extract old emails/handles from snapshots.", input: "{ url }" },
    { name: "http_fingerprint", description: "Live HTTP fetch + headers + title + meta.", when_to_use: "url and subdomain seeds. Feed the body to minimax_extract.", input: "{ url }" },
    { name: "crypto_wallet",  description: "Chain lookup — balance, tx count, related addresses.", when_to_use: "crypto seeds and any wallet address discovered.", input: "{ chain, address }" },
    { name: "google_dorks",   description: "Pre-built Google dork queries.", when_to_use: "Use for targeted public-web discovery; no triage prerequisite.", input: "{ target, kind? }" },
    { name: "dork_harvest",   description: "Run the document/leak dorks and record only the RELEVANT PDFs/Office docs/CSVs/SQL/log/env files + pastebin URLs as artifacts (kind='document' or 'leak_paste'). A hit is recorded only if the seed is in its URL or a bounded Gemini read finds the seed in the document text; irrelevant hits go to candidate_links_unread (not the evidence table). Person seeds use the name-query family.", when_to_use: "Run after google_dorks when document/leak exposure is a justified next step. Turns search queries into VERIFIED recorded evidence, not raw URL noise.", input: "{ seed, kind: email|username|phone|name|person|domain|ip|hash|crypto_wallet, max_queries? }" },
     { name: "gemini_deep_dork", description: "DEEP dork via Gemini 2.5 Flash with native Google Search grounding. Gemini drafts targeted dorks, runs them on real Google, and returns a synthesized writeup + cited URLs (auto-recorded as artifacts). ~$0.002/call.", when_to_use: "Use on corroborated high-value seeds or when standard search coverage is thin. Do not auto-run it on every new selector.", input: "{ seed, kind, focus? }" },
     { name: "gemini_vision", description: "READ an image or document with Gemini Flash (multimodal) — the text-only orchestrator cannot see. mode='image' → {visible_text, watermarks, handles, attributes, scene, confidence} (attributes ONLY — never a face-derived identity; the watermark/@handle/source URL is the anchor; set reverse_search=true to find where the image appears). mode='document' → {extracted_text, tables, selectors, confidence} to actually READ a PDF instead of recording a bare URL. Lead-tier (capped ≤55). ~$0.002/call.", when_to_use: "Route any uploaded/harvested image or PDF here BEFORE reasoning about identity. Read dork-harvested documents that pass the relevance gate instead of recording the URL blind.", input: "{ mode: image|document, url?, base64?, mime_type?, reverse_search?, question? }" },
    { name: "urlscan_search", description: "URLScan.io historical scans for domain/ip/url.", when_to_use: "Use for domain/ip/url context; no triage prerequisite.", input: "{ query }" },
    { name: "minimax_web_search", description: "Live web search with citations powered by Perplexity Sonar. Performs real-time grounded search and returns a synthesized answer plus cited URLs.", when_to_use: "Use for live web pivots. For name/person seeds, search the exact real name before prioritizing derived handles.", input: "{ query, focus? }" },
    { name: "minimax_extract", description: "Extract structured entities (emails/handles/phones/urls/ips/names/etc) from any blob of raw text.", when_to_use: "MANDATORY after any tool returning >500 chars of free-form text. Not rate-limited.", input: "{ text, context? }" },
    { name: "minimax_correlate", description: "Cluster, dedup, rescore confidence, flag contradictions across artifacts.", when_to_use: "After at least three new corroborated artifacts, or when contradiction risk requires re-scoring. Smart-tier model.", input: "{ seed, artifacts[] }" },
    { name: "minimax_plan_pivots", description: "Plan the next bounded execution cycle based on what's been found.", when_to_use: "At the start of each meaningful cycle, before non-planner pivots. Smart-tier model.", input: "{ seed, already_queried[], artifacts[], budget_remaining }" },
    { name: "record_artifacts", description: "Bulk-insert artifacts. THE primary recording call.", when_to_use: "Once per assistant turn with an array of every artifact found this round.", input: "{ artifacts: [{ kind, value, confidence?, source?, metadata? }] }" },
    { name: "record_artifact", description: "Backwards-compatible single-item shim. PREFER record_artifacts.", when_to_use: "Avoid. Use record_artifacts instead.", input: "{ kind, value, confidence?, source?, metadata? }" },
    { name: "record_evidence", description: "Append a tamper-evident chain-of-custody row for a single high-stakes finding (hash-chained, append-only, auditable).", when_to_use: "Any Hard-classified claim, official record, archived URL, or verified breach hit — alongside record_artifacts.", input: "{ classification: 'hard'|'soft', kind, value, source, source_url?, confidence?, notes?, metadata? }" },
    { name: "triage_seed", description: "Optional early classification helper for email or username seeds. Records a `triage_decision` artifact but does not unlock or block other tools.", when_to_use: "Use when cheap baseline context is useful. It is never a prerequisite.", input: "{ seed_value: string, seed_type: string }" },
    { name: "list_tools",     description: "Returns this catalog. Cached per investigation — do not call more than once.", when_to_use: "First turn only, if you need the catalog. Never again.", input: "{}" },
    { name: "deepfind_reverse_email", description: "DeepFind.Me reverse-email account discovery across ~120 services (shared DeepFind 1000/day budget).", when_to_use: "Every confirmed email — finds where the email is registered. High-signal for identity correlation.", input: "{ email }" },
    { name: "deepfind_disposable_email", description: "DeepFind.Me burner/temp email detector.", when_to_use: "Grade every new email's credibility before pivoting on it.", input: "{ email }" },
    { name: "deepfind_ssl_inspect", description: "DeepFind.Me SSL/TLS certificate inspector (issuer, SANs, validity, misconfig warnings).", when_to_use: "Every domain seed — SANs often expose related hostnames worth pivoting on.", input: "{ domain }" },
    { name: "deepfind_tech_stack", description: "DeepFind.Me tech-stack detector (CMS, frameworks, analytics, CDN).", when_to_use: "Every url/domain seed — correlate analytics IDs across sites later.", input: "{ url }" },
    { name: "deepfind_url_unshorten", description: "DeepFind.Me URL unshortener — full redirect chain + safety signal.", when_to_use: "Every short-link discovered (bit.ly, t.co, lnkd.in, ow.ly, etc).", input: "{ url }" },
    { name: "deepfind_telegram_channel", description: "DeepFind.Me Telegram channel metadata + recent messages.", when_to_use: "When a Telegram handle/link is discovered.", input: "{ handle }" },
    { name: "deepfind_telegram_search", description: "DeepFind.Me Telegram channel keyword search.", when_to_use: "When investigating a topic/community and you need to find related channels.", input: "{ query }" },
    { name: "deepfind_vin_lookup", description: "DeepFind.Me VIN decoder (NHTSA vPIC + safety recalls).", when_to_use: "Any 17-char VIN artifact discovered.", input: "{ vin }" },
    { name: "deepfind_aircraft_lookup", description: "DeepFind.Me FAA N-Number lookup (US-registered aircraft → owner of record).", when_to_use: "Any N-Number tail code (e.g. N737AS) discovered.", input: "{ nNumber }" },
    { name: "deepfind_vessel_lookup", description: "DeepFind.Me vessel lookup (IMO / MMSI → vessel + ownership).", when_to_use: "Any IMO or MMSI discovered.", input: "{ identifier }" },
    { name: "deepfind_mac_lookup", description: "DeepFind.Me MAC address → vendor lookup.", when_to_use: "Any MAC address discovered in logs/EXIF/etc.", input: "{ macAddress }" },
    { name: "deepfind_dark_web_link", description: "DeepFind.Me .onion validator + 18k+ service DB check.", when_to_use: "Any .onion URL discovered.", input: "{ url }" },
    { name: "deepfind_email_breach", description: "DeepFind.Me FREE email breach lookup (HIBP-style) — per-breach name/date/PwnCount/DataClasses.", when_to_use: "Any email seed/artifact — free corroborating breach source, and a fallback when stolentax/oathnet/leakcheck are rate-limited. Hits are leads, not confirmed identity.", input: "{ email }" },
    { name: "deepfind_transaction_viewer", description: "DeepFind.Me blockchain transaction lookup by HASH (BTC/ETH/SOL) — sender, receiver, value+USD, fees, token transfers, explorer URL.", when_to_use: "When a transaction hash is the artifact (complements crypto_wallet, which takes an address).", input: "{ hash }" },
    { name: "virustotal_lookup", description: "VirusTotal v3 reputation/detection lookup for file hash, URL, domain, or IP. Public quota: 4/min, 500/day.", when_to_use: "High-value artifacts only — suspicious domains/IPs/URLs surfaced by other tools, or any file hash. Do NOT call on every artifact; reserve for ones already flagged risky.", input: "{ kind:'file'|'url'|'domain'|'ip', value }" },
    { name: "urlscanner_scan", description: "URLScanner.online private URL/domain/IP security scan (sync) — one call returns score (0-100), verdict, DNS, SSL, HTTP headers, WHOIS (incl. domainAge), threat blocklists (URLhaus/Spamhaus/SURBL), and an AI risk summary. Scans are PRIVATE (never made public). Requires URLSCANNER_API_KEY. Quotas: Free 10/day, Solo 100/day, Team 500/day. Typical response 15-20s.", when_to_use: "High-value suspicious URL/domain/IP — phishing/malware triage, link-safety check, or one-shot infra+threat snapshot when you'd otherwise fan-out across virustotal_lookup + urlscan_search + whois_lookup + dns_records. Reserve for flagged artifacts (small daily quota).", input: "{ url }" },
    { name: "ipgeolocation_lookup", description: "IPGeolocation.io secondary IP enrichment — geo, ISP, ASN, connection type, currency, timezone. 1000/day.", when_to_use: "Every ip seed AFTER ip_intel — corroborate or contradict to flag VPN/proxy/mobile.", input: "{ ip }" },
    // ---- Phase 1 free / no-required-key tools (fetch-only corroboration sources) ----
    { name: "ransomwarelive_lookup", description: "Ransomware.live victim-exposure check for a DOMAIN — is it listed as a ransomware/extortion victim? Returns up to 25 victim entries (group, date, description). 404/empty means NOT listed. No API key. Live replacement for the dead deepfind_ransomware_exposure.", when_to_use: "Every non-consumer domain seed and corporate-domain pivot — surfaces breach/extortion context.", input: "{ domain }" },
    { name: "wayback_cdx_search", description: "Wayback Machine CDX archive search — ACCURATE earliest+latest capture (queried separately, not from the capped sample), up to 25 sample capture rows (timestamp, original, statuscode), and `sampled_count`+`capped` (NOT a total count) for a domain/URL. No API key.", when_to_use: "Corroborate that a domain/org/person site existed and when (first-seen / existence claims). Pairs with wayback_snapshots.", input: "{ url }" },
    { name: "crtsh_lookup", description: "crt.sh certificate-transparency lookup for a DOMAIN — unique subdomains + issuer names + cert count (each capped ~50). Can return non-JSON on overload → { error }. No API key.", when_to_use: "Domain seeds — discover subdomains and issuers to pivot on. Complements crtsh_subdomains (which returns subdomains only).", input: "{ domain }" },
    { name: "census_geocode", description: "US Census one-line address geocoder — does a US street ADDRESS exist? Returns the standardized matched address + lon/lat + matched flag. US-only. No API key.", when_to_use: "Verify a US address seed exists and standardize it before further property pivots.", input: "{ address }" },
    { name: "nominatim_geocode", description: "OpenStreetMap Nominatim geocoder — resolve any worldwide ADDRESS/place to coordinates. Returns display_name, lat/lon, category/type, and a residential-vs-commercial hint. Rate-limited 1 req/sec. No API key.", when_to_use: "Geocode/verify a non-US or general address seed, or corroborate census_geocode.", input: "{ address }" },
    { name: "hibp_pwned_passwords_kanon", description: "Have I Been Pwned k-anonymity password-exposure check — { pwned, count } for a password. PRIVACY: only the first 5 chars of the SHA-1 hash ever leave; the password/full hash are never sent. No API key.", when_to_use: "Check whether a discovered/credential password appears in breach corpora. Never on a password you are not authorized to test.", input: "{ password } OR { sha1 }" },
    { name: "gleif_lei_search", description: "GLEIF Legal Entity Identifier registry search by NAME (keyless) — up to 10 entities (lei, legalName, status, jurisdiction, legalAddress {city,country}, registrationStatus). COVERAGE CAVEAT: only entities that hold an LEI (financial-market participants — public companies, funds, many regulated/private orgs); small private companies may be ABSENT, so an empty result does NOT mean the company doesn't exist. No API key.", when_to_use: "Every org/employer/company-name seed or pivot — official, keyless corporate-registry corroboration. Primary registry source now that opencorporates_search needs a key.", input: "{ name }" },
    { name: "opencorporates_search", description: "OpenCorporates company-registry search by NAME — up to 20 companies (name, jurisdiction_code, company_number, incorporation_date, current_status). REQUIRES OPENCORPORATES_API_KEY (keyless requests now 401 'Invalid Api Token'); self-skips with { error } when unset. Prefer gleif_lei_search for keyless registry corroboration.", when_to_use: "Org/employer/company-name seeds ONLY when OPENCORPORATES_API_KEY is configured; otherwise use gleif_lei_search.", input: "{ name }" },
    // ---- Late-injected analytical tools (registered per-request in index.ts
    //      because they need auth context). The LLM sees them here but the
    //      orchestrator wires them up at request time. Keep these in sync
    //      with the (tools as any).* = tool({}) blocks in index.ts.
    { name: "memory_recall", description: "Recall prior agent memory for this user (lessons learned, identity links, recurring patterns, known false positives). Backed by the agent_memory table.", when_to_use: "Call EARLY in any investigation with the seed value AND with each newly confirmed high-value artifact (email, username, domain, wallet). Returns up to 20 most-relevant memory entries. Subject-deduped within a single reasoning step; max 2 calls per 30s window per thread.", input: "{ subject: string, kind?: 'pattern'|'connection'|'lesson'|'identity'|'any', limit?: number }" },
    { name: "memory_save", description: "Persist durable cross-investigation memory (a learned pattern, a confirmed connection, an analyst lesson, or an identity cluster). Backed by the save_agent_memories RPC.", when_to_use: "Call ONCE at the end of the investigation with the strongest connections + any lessons (e.g. 'this domain is always parked', 'this handle resolves to person X', 'breach DB Y has stale phones'). Idempotent: re-saving the same kind+subject+content updates the existing entry. scope='global' = reusable cross-case knowledge (default). scope='case' = facts/decisions tied to THIS investigation only.", input: "{ entries: Array<{kind:'pattern'|'connection'|'lesson'|'identity', subject:string, subject_kind?:string, related_values?:string[], content:string, confidence?:number}>, scope?: 'global'|'case' }" },
    { name: "coverage_audit", description: "Advisory audit of investigative coverage categories against the seed playbook.", when_to_use: "Use to identify gaps when useful; incomplete coverage never blocks progress or reporting.", input: "{}" },
    { name: "detect_contradictions", description: "Examine recorded artifacts and surface identity or infrastructure conflicts.", when_to_use: "Strongly recommended before high-confidence attribution, but never an execution prerequisite.", input: "{ cluster_artifact_kinds?: string[] }" },
    { name: "tool_audit", description: "Advisory tool health and utilization summary for this investigation.", when_to_use: "Use for diagnostics and missed-opportunity review; never as a progress gate.", input: "{}" },
    { name: "record_finding", description: "Persist a source-backed analyst finding. Confidence is computed server-side and Tier-C-only evidence is hard-capped at 50.", when_to_use: "Use whenever source-backed evidence supports a finding. Unsupported claims remain VERIFY/LOW regardless of which audit helpers ran.", input: "{ conclusion: string, cluster_label?: string, supporting_sources: string[], supporting_artifact_values?: string[], drivers: string[], reducers?: string[], contradictions?: string[], unresolved?: string[], next_pivots?: string[], identity_evidence_strength: number, relationship_evidence_strength: number, corroboration_count: number, label?: 'CONFIRMED'|'CORROBORATED'|'INFERRED'|'VERIFY'|'LOW'|'DISMISSED' }" },
    { name: "unknown_tool_ignored", description: "Internal runtime sink — hallucinated or non-registry tool names are redirected here by the unknown-tool guard and dropped without executing the invented tool.", when_to_use: "NEVER call directly. It exists only so the runtime can safely drop invented tool names; call the real tools listed above instead.", input: "{ requested?: string }" },
  ],
  fan_outs: {
    email:    ["Triage is optional context.", "Plan the smallest justified batch from verification, breach corroboration, profile discovery, and open-web context tools.", "Keep single-source or no-hit outputs unverified."],
    username: ["Triage is optional context.", "Start with one identity/profile tool selected by expected value.", "Add a second source for corroboration; do not spray the handle across platforms."],
    phone:    ["Choose one primary phone enrichment source.", "Use a second breach or public-record source only when corroboration or contradiction resolution justifies it.", "Do not expand associated names without direct selector overlap."],
    ip:       ["Start with one network-intelligence source.", "Add geolocation, reverse-host, or reputation checks only when the first result creates a concrete verification question.", "Treat shared/CDN infrastructure as weak linkage."],
    domain:   ["Start with the highest-value domain record source.", "Expand to DNS, certificates, HTTP, or reputation only when each call answers a distinct question.", "Do not pivot every discovered host automatically."],
    subdomain:["Review HTTP or DNS evidence first.", "Pivot an A record to IP analysis only when the infrastructure link is material and not shared/CDN noise."],
    url:      [
      "For a direct supported social URL, normalize the URL and use socialfetch_lookup for that exact platform.",
      "Use jina_reader_scrape for public page content, wayback_snapshots for historical need, or archive_url when preservation is required.",
      "Only pivot extracted selectors after evidence gating.",
    ],
    name:     ["Use a disambiguation search chosen by the planner.", "Keep same-name candidates in separate clusters.", "Require direct selector overlap before profile or paid expansion."],
    "name+location": ["for name+location searches, keep Candidate Identity Clusters separate; never collapse into a single identity"],
    person:   [
      "minimax_web_search(name + location) — primary discovery for person seeds",
      "google_dorks(name)",
      "derive candidate handles (firstlast, first.last, flast) BEFORE any username_sweep call",
      "record candidate identities as SEPARATE clusters",
      "do NOT run username_sweep on the full name/location string — it has spaces and will fail/get skipped",
      "if same-name out-of-area results appear, mark as possible same-name collision and keep in own cluster",
    ],
    crypto:   ["crypto_wallet"],
    breach:   ["Record the breach result with source and timestamp.", "Treat leaked selectors as weak until independently corroborated; never auto-pivot passwords."],
  },
  notes:
    "Tag every finding row with EXACTLY ONE label. [CONFIRMED] = direct profile/source fact OR corroborated by 2+ independent source classes. [INFERRED] = correlated but not definitive. [VERIFY] = needs human check; username_sweep hits and breach-only sensitive identity attributes (DOB, phone, address, full name, SSN) belong here unless corroborated. [FAILED] = tool error / no data. [LOW] = single weak source or possible same-name collision. (Extended labels [CORRELATED] and [CONFLICT] are also supported by the UI parser — see FINDING_LABELS.) For person/name/location seeds, the final report MUST include a Candidate Identity Clusters section whenever multiple same-name candidates appear. Example row: | [CONFIRMED] | `alice@example.com` | breach_check + github_user (2 source classes) | 90% |",
};

// Per-investigation memo so list_tools is effectively free after the first call.
export const CATALOG_CACHE = new Map<string, typeof TOOL_CATALOG>();

// Inline label rule — short enough to keep in the system prompt because the UI
// parser depends on it. Detailed examples live in TOOL_CATALOG.notes.
export const FINDING_LABELS = `
## Finding labels (REQUIRED — UI parser depends on this)
Tag every Findings row with EXACTLY ONE: [CONFIRMED] | [CORRELATED] | [INFERRED] | [VERIFY] | [CONFLICT] | [FAILED] | [LOW].
- CONFIRMED = supported by ≥2 INDEPENDENT source classes (e.g. live profile + WHOIS, or hunter + GitHub), OR a direct first-party source page. Breach data is ONE source class — breach + leak ≠ two classes.
- CORRELATED = multiple artifacts point together but no definitive proof.
- INFERRED = single source states this, not independently corroborated. Default for single-tool hits.
- VERIFY = possible match; needs verification before reporting. username_sweep hits start here unless corroborated.
- CONFLICT = artifact conflicts with the seed (e.g. seed location vs IP geo, different state, different area code) or with another cluster's strong identifier. Use this aggressively to prevent merging two same-name people.
- LOW = weak lead.
- FAILED = false positive or tool failure.

Sensitive PII (DOB, address, phone, SSN, full name) MUST NOT be tagged CONFIRMED on breach-only evidence — cap at INFERRED until a non-breach source corroborates.`;
