/**
 * catalog.ts — Tool catalog, fan-out recipes, catalog cache, and finding labels.
 * Extracted from index.ts (lines 1299–1427).
 * Returned by the `list_tools` meta-tool. Lifted OUT of the system prompt so
 * the prompt stays small. The model calls list_tools at most once per
 * investigation (cached in CATALOG_CACHE keyed by investigation_id).
 */

export type CatalogEntry = { name: string; description: string; when_to_use: string; input: string };

export const TOOL_CATALOG: { tools: CatalogEntry[]; fan_outs: Record<string, string[]>; notes: string } = {
  tools: [
    { name: "emailrep",       description: "Reputation score, profile presence, suspicious-domain flag for an email.", when_to_use: "Cheap Stage-1 signal for emails. Auto-fired by triage_seed.", input: "{ email: string }" },
    { name: "gravatar_profile", description: "Gravatar lookup — confirms a real avatar/profile linked to an email.", when_to_use: "Cheap Stage-1 signal for emails. Auto-fired by triage_seed.", input: "{ email: string }" },
    { name: "breach_check",   description: "MAIN breach source — stolen.tax (1000 calls/day). Queries OsintCat database-search (email+password combos), Snusbase (identity records: name/phone/address/DOB), and OsintCat breach. Returns combined hit count plus per-source samples.", when_to_use: "Default breach lookup for original email seeds and corroborated follow-on selectors. Do NOT auto-expand single-source weak leads or collisions with it.", input: "{ email?: string, value?: string }" },
    { name: "stolentax_footprint", description: "stolen.tax OsintCat-Footprint — account-discovery sweep across ~127 sites. Complements deepfind_reverse_email with a different site list and richer per-site metadata.", when_to_use: "Every confirmed email and every promising username. Pair with deepfind_reverse_email for the widest account-discovery coverage.", input: "{ value: string, type?: 'auto'|'email'|'username' }" },
    { name: "leakcheck_lookup", description: "SECONDARY breach source — LeakCheck Pro v2 (200 calls/day). Returns leak sources, breach dates, and where present passwords/usernames for an email, username, or phone.", when_to_use: "Corroborate breach_check on confirmed emails and high-value handles. Especially valuable when breach_check returns 0 hits or thin data, or you want password/source detail. Do not spam on weak handles — 200/day budget.", input: "{ value: string, type?: 'auto'|'email'|'username'|'phone'|'hash'|'domain' }" },
    { name: "hibp_lookup", description: "Have I Been Pwned v3 — Troy Hunt's authoritative breach + paste corpus. Returns breach metadata (name, domain, date, data classes) for an email. Rate: 1 req/1.5s.", when_to_use: "Corroborate breach_check + leakcheck_lookup on every CONFIRMED email seed. Skip on speculative addresses.", input: "{ email, include_pastes?, truncate? }" },
    { name: "intelbase_email_lookup", description: "IntelBase email lookup — aggregated breach + profile modules. GATED OFF by default: unavailable unless INTELBASE_ENABLED is set (the provider was disabled for instability), so it is removed from the live tool set on most runs.", when_to_use: "Do not rely on it. Only usable if an operator has explicitly enabled INTELBASE_ENABLED; it is never part of the default email fan-out. Use breach_check / leakcheck_lookup / oathnet_lookup / bosint_email_lookup instead.", input: "{ email, include_data_breaches?, timeout_ms?, exclude_modules? }" },
    { name: "bosint_email_lookup", description: "OSINTNova (Bosint) email exposure check — surface-level breach + exposure indicators. 1000/day shared with bosint_phone_lookup.", when_to_use: "Use once per justified email seed or confirmed follow-on email when it adds corroboration value.", input: "{ email }" },
    { name: "bosint_phone_lookup", description: "OSINTNova (Bosint) phone intelligence — carrier, location, line type, timezone, associated names. 1000/day shared with bosint_email_lookup.", when_to_use: "Use once per justified phone seed when it adds corroboration or contradiction-resolution value.", input: "{ phone }" },
    { name: "osint_navigator_query", description: "OSINT Navigator (navigator.indicator.media) — natural-language tool recommendation. Returns curated, verified OSINT tools (name + URL) for the asked workflow. Use to discover the right third-party tool to suggest to the user; do NOT invent tools.", when_to_use: "When the user asks for tool recommendations, or when planning a pivot you don't already have a wired tool for and want to point the user at a vetted external tool.", input: "{ query: string, skip_cache?: boolean }" },
    { name: "osint_navigator_search", description: "OSINT Navigator direct keyword/category tool-database search. Categories: domains_websites, social_media, image_video_analysis, geolocation_mapping, transport, companies.", when_to_use: "Browsing alternatives or when you already know the category. Pair with osint_navigator_query for natural-language follow-ups.", input: "{ query: string, category?: string, limit?: number }" },
     { name: "oathnet_lookup", description: "Corroborating leaked-data + identity source. v2 breach search for email/username/phone/domain; geo+ASN for ip. 100 calls/day.", when_to_use: "Use once per corroborated high-value selector or contradiction-resolution target. Do not spend it on display-name clues, same-name collisions, or no-hit follow-ups.", input: "{ kind, value }" },
    { name: "serus_darkweb_scan", description: "Serus darkweb exposure scan (api.serus.ai). One tool, seven identifier types: email, phone, username, domain, keyword, origin (IP/hostname), password. Initiates a scan and polls until completion (~5–30s). Returns breach count + breach names + data classes (masked by default; pass reveal:true to unmask passwords/tokens if the key has darkweb:reveal scope), paste count, and any extracted PII (emails, usernames, phones, names, crypto addresses). 0.25 credits per scan, 3 req/s write budget.", when_to_use: "SECONDARY / CORROBORATING breach source. Use only when the planner identifies independent-corpus value for a confirmed selector or contradiction. Use identifierType:'origin' for IP/hostname. Use identifierType:'password' only on confirmed seeds you own or are authorized to test. Pass reveal:true ONLY when the user explicitly authorizes unmasked breach data — it costs extra credits and is sensitive.", input: "{ identifierType: 'email'|'phone'|'username'|'domain'|'keyword'|'origin'|'password', identifierValue: string, reveal?: boolean }" },
    { name: "ipqualityscore_lookup", description: "IPQualityScore validity + fraud scoring (ipqualityscore.com). One tool, three identifier types: phone | email | ip. Returns valid flag + 0-100 fraud_score + type-specific signals (phone: active, line_type, carrier, CNAM name, recent_abuse; email: deliverability, disposable, leaked, names; ip: proxy/vpn/tor, bot_status, recent_abuse, connection_type). Free tier ~5000/mo.", when_to_use: "VALIDATION GATE — run EARLY on a phone/email/ip seed before spending on deep breach/people-search. If valid:false or fraud_score>=85, the identifier is reserved/fake/disposable: treat attributions to it as low-confidence and stop spending paid calls on it. Also a strong corroborator (carrier/line-type/name for phones; deliverability/leaked for emails; proxy/vpn for IPs).", input: "{ kind: 'phone'|'email'|'ip', value: string, country?: string }" },
    { name: "synapsint_lookup", description: "Synapsint multi-endpoint aggregator. Endpoints: links/subdomains/dns/waf/tenant/leaks/whoisd/dmarc/sh/tls/ranking/pastes/dnssec (domain); check/rip/whoiss (ip); asn; email; cve. Free-tier quota.", when_to_use: "Secondary corroboration for domain/ip/email/cve/asn seeds. Especially useful for rip (shared-hosting neighbors), tenant (M365), pastes, and domain-wide leaks that other tools don't cover.", input: "{ endpoint, value }" },
    { name: "socialfetch_lookup", description: "PRIMARY profile fetch for tiktok/instagram/twitter/facebook handles (10k credit pool).", when_to_use: "FIRST choice on corroborated handles or direct profile URLs for tiktok/instagram/twitter/facebook. Do not spray it across every platform for weak or colliding handles. Fall back to jina_reader_scrape if SocialFetch errors.", input: "{ platform, username }" },
    { name: "cordcat_discord_lookup", description: "CordCat Discord OSINT — given a 17-20 digit Discord snowflake ID, returns Discord profile (username, global_name, avatar, banner, public_flags), breach hits, FiveM records, and DSA sanction statements.", when_to_use: "Every Discord snowflake ID surfaced as a seed or pivot. The Discord username alone is NOT enough — extract the numeric ID first (e.g. via jina_reader_scrape on a Discord profile/invite page). 60 req/hour budget.", input: "{ discord_id: string }" },
    { name: "jina_reader_scrape", description: "ONLY single-page scraper. Free Jina Reader returns clean LLM-ready markdown for any public URL.", when_to_use: "Default for a specific source page: profile pages, articles, forums, leak listings, dork hits, Discord/Telegram web links, and similar source material.", input: "{ url, maxChars? }" },
    { name: "exa_search", description: "Exa neural+keyword search with optional inline contents. Categories: company, research paper, news, pdf, github, tweet, personal site, linkedin profile, financial report. Date-bounded via startPublishedDate/endPublishedDate.", when_to_use: "PRIMARY semantic web search when it clearly adds value. Pair with minimax_web_search only when corroboration or broader coverage is justified.", input: "{ query, type?, numResults?, includeDomains?, excludeDomains?, startPublishedDate?, endPublishedDate?, category?, contents? }" },
    { name: "exa_find_similar", description: "Exa findSimilar — given a known URL, return semantically similar pages.", when_to_use: "After confirming any single profile URL (linkedin profile, personal site, github, twitter) — use to find the same person's other profiles or related entities. Powerful identity-pivot tool.", input: "{ url, numResults?, excludeSourceDomain?, contents? }" },
    { name: "exa_get_contents", description: "Exa /contents — fetch full text + AI summary + highlights for up to 10 URLs in one call. Best for bulk URL reading.", when_to_use: "When you have several URLs from exa_search / dorks and want their text in one batch instead of N jina_reader_scrape calls. Set livecrawl='always' for breaking news or pages you suspect Exa has cached stale.", input: "{ urls: string[], livecrawl?, text?, highlights?, summary?, maxCharacters? }" },
    { name: "ip_intel",       description: "IP geolocation, ASN, hosting info.", when_to_use: "Every ip seed and every IP discovered from DNS.", input: "{ ip: string }" },
    { name: "shodan_internetdb", description: "Open ports, vulns, cert subjects for an IP/domain via Shodan InternetDB.", when_to_use: "ip seeds and on resolved IPs of domain seeds.", input: "{ value }" },
    { name: "whois_lookup",   description: "RDAP/WHOIS registrant data for a domain.", when_to_use: "Every domain seed. Pivot on registrant email/name.", input: "{ domain }" },
    { name: "dns_records",    description: "A/AAAA/MX/NS/TXT/CNAME/SOA/CAA records + email-auth virtuals (SPF/DMARC/DKIM/BIMI, auto-translated to TXT).", when_to_use: "Every domain seed. Pivot on returned IPs and MX hostnames. For email-auth posture pass SPF/DMARC/DKIM (DKIM needs dkimSelector) — never query SPF as a real record type.", input: "{ host, types?: string[], dkimSelector? }" },
    { name: "crtsh_subdomains", description: "Certificate-transparency subdomain discovery.", when_to_use: "Every domain seed. Each subdomain → http_fingerprint.", input: "{ domain }" },
    { name: "hackertarget",   description: "Reverse-IP and hostsearch via hackertarget.com.", when_to_use: "domain (hostsearch) and ip (reverseiplookup) seeds.", input: "{ kind, value }" },
    { name: "username_sweep", description: "Built-in Username Sweep: parallel HTTP existence check across ~95 platforms for a handle. Edge-native. Only call this on a handle with NO spaces. Do NOT call it on a full name or name+location seed — derive candidate handles first.", when_to_use: "Every username/handle. Results are [VERIFY] — never confirmed alone.", input: "{ username }" },
    { name: "username_search", description: "DEPRECATED alias of username_sweep — identical built-in ~95-site existence check, kept only for backwards compatibility with saved runs. Same no-spaces rule applies.", when_to_use: "Do not call directly — prefer username_sweep. Retained as an alias so older saved runs that reference this name still resolve.", input: "{ username, platforms? }" },
    { name: "github_user",    description: "GitHub profile, public emails, repos, bio.", when_to_use: "Every username seed and on github.com hits from sweep.", input: "{ username }" },
    { name: "github_code_search", description: "Search public GitHub code for a string.", when_to_use: "Stage 2 (gated): non-consumer domain only. Find leaks/configs that mention the seed.", input: "{ query }" },
    { name: "hunter_domain_search", description: "Hunter.io domain search — emails associated with a domain plus department/seniority/sources.", when_to_use: "Every non-consumer domain seed and every domain pivoted from an email. Cheap and high-signal.", input: "{ domain, limit?, department?, seniority? }" },
    { name: "hunter_email_finder", description: "Hunter.io email finder — guess + verify an email from a person's name and a domain.", when_to_use: "When you have a name + corporate domain pair and want a likely email.", input: "{ domain, first_name?, last_name?, full_name? }" },
    { name: "hunter_email_verifier", description: "Hunter.io deliverability + risk verification for an email address.", when_to_use: "Run on any new high-value email to grade confidence (deliverable / risky / undeliverable, MX, SMTP, disposable, webmail).", input: "{ email }" },
    { name: "hunter_combined", description: "Hunter.io combined person + company enrichment for an email.", when_to_use: "Run on every confirmed email — returns name, role, social links, company info, employee count, tech stack.", input: "{ email }" },
    { name: "archive_url", description: "Submit a URL to the Wayback Machine to create a permanent archived snapshot (chain of custody).", when_to_use: "After confirming any evidence URL that may disappear (social posts, leak listings, scam sites). Required for [CONFIRMED] findings on volatile sources.", input: "{ url }" },
    { name: "hackernews_user",description: "Hacker News profile + recent comments.", when_to_use: "Every username seed.", input: "{ username }" },
    { name: "reddit_user",    description: "Reddit profile + recent activity.", when_to_use: "Every username seed.", input: "{ username }" },
    { name: "wayback_snapshots", description: "Wayback Machine snapshot index for a URL.", when_to_use: "url seeds. Extract old emails/handles from snapshots.", input: "{ url }" },
    { name: "http_fingerprint", description: "Live HTTP fetch + headers + title + meta.", when_to_use: "url and subdomain seeds. Feed the body to minimax_extract.", input: "{ url }" },
    { name: "crypto_wallet",  description: "Chain lookup — balance, tx count, related addresses.", when_to_use: "crypto seeds and any wallet address discovered.", input: "{ chain, address }" },
    { name: "google_dorks",   description: "Pre-built Google dork queries.", when_to_use: "Stage 2 (gated): requires a known name or username artifact.", input: "{ target, kind? }" },
    { name: "dork_harvest",   description: "Run the document/leak dorks and AUTO-RECORD any PDFs/Office docs/CSVs/SQL/log/env files + pastebin URLs as artifacts (kind='document' or 'leak_paste'). Person seeds are accepted and use the name-query family.", when_to_use: "Run after google_dorks when document/leak exposure is a justified next step. This turns search queries into recorded evidence.", input: "{ seed, kind: email|username|phone|name|person|domain|ip|hash|crypto_wallet, max_queries? }" },
     { name: "gemini_deep_dork", description: "DEEP dork via Gemini 2.5 Flash with native Google Search grounding. Gemini drafts targeted dorks, runs them on real Google, and returns a synthesized writeup + cited URLs (auto-recorded as artifacts). ~$0.002/call.", when_to_use: "Use on corroborated high-value seeds or when standard search coverage is thin. Do not auto-run it on every new selector.", input: "{ seed, kind, focus? }" },
    { name: "urlscan_search", description: "URLScan.io historical scans for domain/ip/url.", when_to_use: "Stage 2 (gated). Every domain/ip/url seed.", input: "{ query }" },
    { name: "minimax_web_search", description: "Live web search with citations powered by Perplexity Sonar. Performs real-time grounded search and returns a synthesized answer plus cited URLs.", when_to_use: "Stage 2 gated search. Use for quick live web pivots on seeds, emails, handles, names, domains, and URLs before deeper analysis.", input: "{ query, focus? }" },
    { name: "minimax_extract", description: "Extract structured entities (emails/handles/phones/urls/ips/names/etc) from any blob of raw text.", when_to_use: "MANDATORY after any tool returning >500 chars of free-form text. Not rate-limited.", input: "{ text, context? }" },
    { name: "minimax_correlate", description: "Cluster, dedup, rescore confidence, flag contradictions across artifacts.", when_to_use: "After at least three new corroborated artifacts, or when contradiction risk requires re-scoring. Smart-tier model.", input: "{ seed, artifacts[] }" },
    { name: "minimax_plan_pivots", description: "Plan the next bounded execution cycle based on what's been found.", when_to_use: "At the start of each meaningful cycle, before non-planner pivots. Smart-tier model.", input: "{ seed, already_queried[], artifacts[], budget_remaining }" },
    { name: "record_artifacts", description: "Bulk-insert artifacts. THE primary recording call.", when_to_use: "Once per assistant turn with an array of every artifact found this round.", input: "{ artifacts: [{ kind, value, confidence?, source?, metadata? }] }" },
    { name: "record_artifact", description: "Backwards-compatible single-item shim. PREFER record_artifacts.", when_to_use: "Avoid. Use record_artifacts instead.", input: "{ kind, value, confidence?, source?, metadata? }" },
    { name: "record_evidence", description: "Append a tamper-evident chain-of-custody row for a single high-stakes finding (hash-chained, append-only, auditable).", when_to_use: "Any Hard-classified claim, official record, archived URL, or verified breach hit — alongside record_artifacts.", input: "{ classification: 'hard'|'soft', kind, value, source, source_url?, confidence?, notes?, metadata? }" },
    { name: "triage_seed", description: "MANDATORY first step for email or username seeds. Runs the cheap Stage-1 tools (emailrep, gravatar_profile, breach_check) first, then decides which Stage-2 tools are eligible. Records a `triage_decision` artifact.", when_to_use: "ALWAYS first turn for email or username seeds. Never on phone/ip/domain/url/keyword — those have different playbooks.", input: "{ seed_value: string, seed_type: string }" },
    { name: "list_tools",     description: "Returns this catalog. Cached per investigation — do not call more than once.", when_to_use: "First turn only, if you need the catalog. Never again.", input: "{}" },
    { name: "deepfind_reverse_email", description: "DeepFind.Me reverse-email account discovery across ~120 services (shared DeepFind 1000/day budget).", when_to_use: "Every confirmed email — finds where the email is registered. High-signal for identity correlation.", input: "{ email }" },
    { name: "deepfind_disposable_email", description: "DeepFind.Me burner/temp email detector.", when_to_use: "Grade every new email's credibility before pivoting on it.", input: "{ email }" },
    { name: "deepfind_ransomware_exposure", description: "DeepFind.Me ransomware leak-site exposure check.", when_to_use: "Every non-consumer domain seed and every corporate email — surfaces breach/extortion context.", input: "{ query }" },
    { name: "deepfind_ssl_inspect", description: "DeepFind.Me SSL/TLS certificate inspector (issuer, SANs, validity, misconfig warnings).", when_to_use: "Every domain seed — SANs often expose related hostnames worth pivoting on.", input: "{ domain }" },
    { name: "deepfind_tech_stack", description: "DeepFind.Me tech-stack detector (CMS, frameworks, analytics, CDN).", when_to_use: "Every url/domain seed — correlate analytics IDs across sites later.", input: "{ url }" },
    { name: "deepfind_url_unshorten", description: "DeepFind.Me URL unshortener — full redirect chain + safety signal.", when_to_use: "Every short-link discovered (bit.ly, t.co, lnkd.in, ow.ly, etc).", input: "{ url }" },
    { name: "deepfind_profile_analyzer", description: "DeepFind.Me deep username sweep across ~350 sites (vs local sweep's ~95). Slow.", when_to_use: "High-value handles only, or when the local username_sweep returned thin coverage. Burns budget — do not spam.", input: "{ username }" },
    { name: "deepfind_telegram_channel", description: "DeepFind.Me Telegram channel metadata + recent messages.", when_to_use: "When a Telegram handle/link is discovered.", input: "{ handle }" },
    { name: "deepfind_telegram_search", description: "DeepFind.Me Telegram channel keyword search.", when_to_use: "When investigating a topic/community and you need to find related channels.", input: "{ query }" },
    { name: "deepfind_vin_lookup", description: "DeepFind.Me VIN decoder (NHTSA vPIC + safety recalls).", when_to_use: "Any 17-char VIN artifact discovered.", input: "{ vin }" },
    { name: "deepfind_aircraft_lookup", description: "DeepFind.Me FAA N-Number lookup (US-registered aircraft → owner of record).", when_to_use: "Any N-Number tail code (e.g. N737AS) discovered.", input: "{ nNumber }" },
    { name: "deepfind_vessel_lookup", description: "DeepFind.Me vessel lookup (IMO / MMSI → vessel + ownership).", when_to_use: "Any IMO or MMSI discovered.", input: "{ identifier }" },
    { name: "deepfind_mac_lookup", description: "DeepFind.Me MAC address → vendor lookup.", when_to_use: "Any MAC address discovered in logs/EXIF/etc.", input: "{ macAddress }" },
    { name: "deepfind_dark_web_link", description: "DeepFind.Me .onion validator + 18k+ service DB check.", when_to_use: "Any .onion URL discovered.", input: "{ url }" },
    { name: "deepfind_email_breach", description: "DeepFind.Me FREE email breach lookup (HIBP-style) — per-breach name/date/PwnCount/DataClasses.", when_to_use: "Any email seed/artifact — free corroborating breach source, and a fallback when stolentax/oathnet/leakcheck are rate-limited. Hits are leads, not confirmed identity.", input: "{ email }" },
    { name: "deepfind_transaction_viewer", description: "DeepFind.Me blockchain transaction lookup by HASH (BTC/ETH/SOL) — sender, receiver, value+USD, fees, token transfers, explorer URL.", when_to_use: "When a transaction hash is the artifact (complements crypto_wallet, which takes an address).", input: "{ hash }" },
    { name: "virustotal_lookup", description: "VirusTotal v3 reputation/detection lookup for file hash, URL, domain, or IP. Public quota: 4/min, 500/day.", when_to_use: "High-value artifacts only — suspicious domains/IPs/URLs surfaced by other tools, or any file hash. Do NOT call on every artifact; reserve for ones already flagged risky.", input: "{ kind:'file'|'url'|'domain'|'ip', value }" },
    { name: "ipgeolocation_lookup", description: "IPGeolocation.io secondary IP enrichment — geo, ISP, ASN, connection type, currency, timezone. 1000/day.", when_to_use: "Every ip seed AFTER ip_intel — corroborate or contradict to flag VPN/proxy/mobile.", input: "{ ip }" },
    // ---- Disabled stubs (intentionally kept in the runtime + catalog so
    //      the LLM gets a helpful "this is disabled, use X instead" error
    //      instead of a "tool does not exist" error if it tries to call one).
    { name: "firecrawl_search", description: "DISABLED STUB. Firecrawl credits exhausted. Do NOT call — use an eligible search tool instead.", when_to_use: "Never. Let the planner choose either exa_search or minimax_web_search based on expected value.", input: "{ query: string, limit?: number, tbs?: string, country?: string, lang?: string, sources?: string[], scrape?: boolean }" },
    { name: "firecrawl_scrape", description: "DISABLED STUB. Firecrawl credits exhausted. Do NOT call — use jina_reader_scrape instead.", when_to_use: "Never. Swap to jina_reader_scrape({ url }).", input: "{ url: string, formats?: string[], onlyMainContent?: boolean, waitFor?: number }" },
    { name: "firecrawl_map", description: "DISABLED STUB. Firecrawl credits exhausted. Do NOT call — use crtsh_subdomains + dns_records instead.", when_to_use: "Never. Swap to crtsh_subdomains + dns_records for domain enumeration.", input: "{ url: string, search?: string, limit?: number, includeSubdomains?: boolean }" },
    // ---- Late-injected analytical tools (registered per-request in index.ts
    //      because they need auth context). The LLM sees them here but the
    //      orchestrator wires them up at request time. Keep these in sync
    //      with the (tools as any).* = tool({}) blocks in index.ts.
    { name: "memory_recall", description: "Recall prior agent memory for this user (lessons learned, identity links, recurring patterns, known false positives). Backed by the agent_memory table.", when_to_use: "Call EARLY in any investigation with the seed value AND with each newly confirmed high-value artifact (email, username, domain, wallet). Returns up to 20 most-relevant memory entries. Subject-deduped within a single reasoning step; max 2 calls per 30s window per thread.", input: "{ subject: string, kind?: 'pattern'|'connection'|'lesson'|'identity'|'any', limit?: number }" },
    { name: "memory_save", description: "Persist durable cross-investigation memory (a learned pattern, a confirmed connection, an analyst lesson, or an identity cluster). Backed by the save_agent_memories RPC.", when_to_use: "Call ONCE at the end of the investigation with the strongest connections + any lessons (e.g. 'this domain is always parked', 'this handle resolves to person X', 'breach DB Y has stale phones'). Idempotent: re-saving the same kind+subject+content updates the existing entry. scope='global' = reusable cross-case knowledge (default). scope='case' = facts/decisions tied to THIS investigation only.", input: "{ entries: Array<{kind:'pattern'|'connection'|'lesson'|'identity', subject:string, subject_kind?:string, related_values?:string[], content:string, confidence?:number}>, scope?: 'global'|'case' }" },
    { name: "coverage_audit", description: "Audit the 12 investigative coverage categories (identity/email/username/phone/domain/infrastructure/social/breach/location/employment/relationships/timeline) against the playbook for this seed type. Returns {complete, categories, missingOpportunities}.", when_to_use: "MANDATORY before record_finding. If complete=false you MUST either run the missing tools or mark the case 'incomplete' in the final report. Takes no arguments.", input: "{}" },
    { name: "detect_contradictions", description: "Examine the artifacts already recorded for this investigation and surface conflicts (location mismatch, employer mismatch, common-handle collision, CDN/shared-infra false-link, stale breach data, thin same-name). Each contradiction reduces relevant confidence axes.", when_to_use: "MANDATORY before record_finding. Optional cluster_artifact_kinds to restrict scope.", input: "{ cluster_artifact_kinds?: string[] }" },
    { name: "tool_audit", description: "Tool health + API utilization for this investigation: which Tier-A APIs were configured, which were called, which were skipped without justification ('missed_opportunity'), failure counts per tool, artifact yield per tool, total cost in USD.", when_to_use: "MANDATORY before record_finding. Takes no arguments.", input: "{}" },
    { name: "record_finding", description: "Persist an analyst-grade FINDING (distinct from a raw artifact). Each finding must cite supporting artifacts, name drivers and reducers, and acknowledge contradictions. Confidence is computed server-side from sources + corroboration + contradictions; the input 'confidence' field is treated as a target, not a guarantee. Tier-C-only evidence is hard-capped at 50.", when_to_use: "Use ONLY after coverage_audit + detect_contradictions + tool_audit have run. Required fields: conclusion, supporting_sources, drivers, corroboration_count, identity_evidence_strength, relationship_evidence_strength.", input: "{ conclusion: string, cluster_label?: string, supporting_sources: string[], supporting_artifact_values?: string[], drivers: string[], reducers?: string[], contradictions?: string[], unresolved?: string[], next_pivots?: string[], identity_evidence_strength: number, relationship_evidence_strength: number, corroboration_count: number, label?: 'CONFIRMED'|'CORROBORATED'|'INFERRED'|'VERIFY'|'LOW'|'DISMISSED' }" },
  ],
  fan_outs: {
    email:    ["Run triage_seed first.", "Plan the smallest justified batch from verification, breach corroboration, profile discovery, and open-web context tools.", "Do not expand single-source or no-hit outputs automatically."],
    username: ["Run triage_seed first.", "Start with one identity/profile tool selected by expected value.", "Add a second source only for corroboration; do not spray the handle across platforms."],
    phone:    ["Choose one primary phone enrichment source.", "Use a second breach or public-record source only when corroboration or contradiction resolution justifies it.", "Do not expand associated names without direct selector overlap."],
    ip:       ["Start with one network-intelligence source.", "Add geolocation, reverse-host, or reputation checks only when the first result creates a concrete verification question.", "Treat shared/CDN infrastructure as weak linkage."],
    domain:   ["Start with the highest-value domain record source.", "Expand to DNS, certificates, HTTP, or reputation only when each call answers a distinct question.", "Do not pivot every discovered host automatically."],
    subdomain:["Review HTTP or DNS evidence first.", "Pivot an A record to IP analysis only when the infrastructure link is material and not shared/CDN noise."],
    url:      [
      "For a direct supported social URL, normalize the URL and use socialfetch_lookup for that exact platform.",
      "Use jina_reader_scrape for public page content, wayback_snapshots for historical need, or archive_url when preservation is required.",
      "Only pivot extracted selectors after evidence gating.",
    ],
    name:     ["Use a disambiguation search chosen by the planner.", "Keep same-name candidates in separate clusters.", "Require direct selector overlap before profile or paid expansion."],
    "name+location": ["for name+location searches, keep Candidate Identity Clusters separate; never collapse into a single identity"],
    person:   [
      "minimax_web_search(name + location) — primary discovery for person seeds",
      "google_dorks(name)",
      "derive candidate handles (firstlast, first.last, flast) BEFORE any username_sweep call",
      "record candidate identities as SEPARATE clusters",
      "do NOT run username_sweep on the full name/location string — it has spaces and will fail/get skipped",
      "if same-name out-of-area results appear, mark as possible same-name collision and keep in own cluster",
    ],
    crypto:   ["crypto_wallet"],
    breach:   ["Record the breach result with source and timestamp.", "Treat leaked selectors as weak until independently corroborated; never auto-pivot passwords."],
  },
  notes:
    "Tag every finding row with EXACTLY ONE label. [CONFIRMED] = direct profile/source fact OR corroborated by 2+ independent source classes. [INFERRED] = correlated but not definitive. [VERIFY] = needs human check; username_sweep hits and breach-only sensitive identity attributes (DOB, phone, address, full name, SSN) belong here unless corroborated. [FAILED] = tool error / no data. [LOW] = single weak source or possible same-name collision. (Extended labels [CORRELATED] and [CONFLICT] are also supported by the UI parser — see FINDING_LABELS.) For person/name/location seeds, the final report MUST include a Candidate Identity Clusters section whenever multiple same-name candidates appear. Example row: | [CONFIRMED] | `alice@example.com` | breach_check + github_user (2 source classes) | 90% |",
};

// Per-investigation memo so list_tools is effectively free after the first call.
export const CATALOG_CACHE = new Map<string, typeof TOOL_CATALOG>();

// Inline label rule — short enough to keep in the system prompt because the UI
// parser depends on it. Detailed examples live in TOOL_CATALOG.notes.
export const FINDING_LABELS = `
## Finding labels (REQUIRED — UI parser depends on this)
Tag every Findings row with EXACTLY ONE: [CONFIRMED] | [CORRELATED] | [INFERRED] | [VERIFY] | [CONFLICT] | [FAILED] | [LOW].
- CONFIRMED = supported by ≥2 INDEPENDENT source classes (e.g. live profile + WHOIS, or hunter + GitHub), OR a direct first-party source page. Breach data is ONE source class — breach + leak ≠ two classes.
- CORRELATED = multiple artifacts point together but no definitive proof.
- INFERRED = single source states this, not independently corroborated. Default for single-tool hits.
- VERIFY = possible match; needs verification before reporting. username_sweep hits start here unless corroborated.
- CONFLICT = artifact conflicts with the seed (e.g. seed location vs IP geo, different state, different area code) or with another cluster's strong identifier. Use this aggressively to prevent merging two same-name people.
- LOW = weak lead.
- FAILED = false positive or tool failure.

Sensitive PII (DOB, address, phone, SSN, full name) MUST NOT be tagged CONFIRMED on breach-only evidence — cap at INFERRED until a non-breach source corroborates.`;
