/**
 * catalog.ts — Tool catalog, fan-out recipes, catalog cache, and finding labels.
 * Extracted from index.ts (lines 1299–1427).
 * Returned by the `list_tools` meta-tool. Lifted OUT of the system prompt so
 * the prompt stays small. The model calls list_tools at most once per
 * investigation (cached in CATALOG_CACHE keyed by investigation_id).
 */

export type CatalogEntry = { name: string; description: string; when_to_use: string; input: string };

export const TOOL_CATALOG: { tools: CatalogEntry[]; fan_outs: Record<string, string[]>; notes: string } = {
  tools: [
    { name: "triage_seed", description: "MANDATORY first call for email/username seeds. Runs Stage-1 cheap tools in parallel and decides which Stage-2 expensive tools unlock.", when_to_use: "First tool call on email or username seeds. Never on ip/domain/phone/url/crypto.", input: "{ seed: string, type: 'email'|'username' }" },
    { name: "emailrep",       description: "Reputation score, profile presence, suspicious-domain flag for an email.", when_to_use: "Cheap Stage-1 signal for emails. Auto-fired by triage_seed.", input: "{ email: string }" },
    { name: "gravatar_profile", description: "Gravatar lookup — confirms a real avatar/profile linked to an email.", when_to_use: "Cheap Stage-1 signal for emails. Auto-fired by triage_seed.", input: "{ email: string }" },
    { name: "breach_check",   description: "MAIN breach source — stolen.tax (1000 calls/day). Now fans out in parallel to OsintCat database-search (email+password combos), Snusbase (identity records: name/phone/address/DOB), and OsintCat breach. Returns combined hit count plus per-source samples.", when_to_use: "Default breach lookup. Auto-fired by triage_seed. Run again on every newly found email or promising username — budget is generous. Run minimax_extract on data.raw to pull names/phones/addresses out of Snusbase results.", input: "{ email?: string, value?: string }" },
    { name: "stolentax_footprint", description: "stolen.tax OsintCat-Footprint — account-discovery sweep across ~127 sites. Complements deepfind_reverse_email with a different site list and richer per-site metadata.", when_to_use: "Every confirmed email and every promising username. Pair with deepfind_reverse_email for the widest account-discovery coverage.", input: "{ value: string, type?: 'auto'|'email'|'username' }" },
    { name: "leakcheck_lookup", description: "SECONDARY breach source — LeakCheck Pro v2 (200 calls/day). Returns leak sources, breach dates, and where present passwords/usernames for an email, username, or phone.", when_to_use: "Corroborate breach_check on confirmed emails and high-value handles. Especially valuable when breach_check returns 0 hits or thin data, or you want password/source detail. Do not spam on weak handles — 200/day budget.", input: "{ value: string, type?: 'auto'|'email'|'username'|'phone'|'hash'|'domain' }" },
    { name: "hibp_lookup", description: "Have I Been Pwned v3 — Troy Hunt's authoritative breach + paste corpus. Returns breach metadata (name, domain, date, data classes) for an email. Rate: 1 req/1.5s.", when_to_use: "Corroborate breach_check + leakcheck_lookup on every CONFIRMED email seed. Skip on speculative addresses.", input: "{ email, include_pastes?, truncate? }" },
    { name: "intelbase_email_lookup", description: "IntelBase email lookup — aggregated breach + profile modules with optional data-breach detail. Primary email enrichment source (unlimited on current plan).", when_to_use: "Stage 2 (gated). FIRST choice for email seeds — run BEFORE oathnet_lookup to preserve the daily oathnet quota.", input: "{ email, include_data_breaches?, timeout_ms?, exclude_modules? }" },
    { name: "bosint_email_lookup", description: "OSINTNova (Bosint) email exposure check — surface-level breach + exposure indicators. 1000/day shared with bosint_phone_lookup.", when_to_use: "Fire ONCE per email seed and once per newly-confirmed email mid-run, in parallel with breach_check / leakcheck_lookup / intelbase_email_lookup / oathnet_lookup.", input: "{ email }" },
    { name: "bosint_phone_lookup", description: "OSINTNova (Bosint) phone intelligence — carrier, location, line type, timezone, associated names. 1000/day shared with bosint_email_lookup.", when_to_use: "Fire ONCE per phone seed (E.164 with country code) in parallel with leakcheck_lookup + oathnet_lookup. Best phone enrichment we have.", input: "{ phone }" },
    { name: "osint_navigator_query", description: "OSINT Navigator (navigator.indicator.media) — natural-language tool recommendation. Returns curated, verified OSINT tools (name + URL) for the asked workflow. Use to discover the right third-party tool to suggest to the user; do NOT invent tools.", when_to_use: "When the user asks for tool recommendations, or when planning a pivot you don't already have a wired tool for and want to point the user at a vetted external tool.", input: "{ query: string, skip_cache?: boolean }" },
    { name: "osint_navigator_search", description: "OSINT Navigator direct keyword/category tool-database search. Categories: domains_websites, social_media, image_video_analysis, geolocation_mapping, transport, companies.", when_to_use: "Browsing alternatives or when you already know the category. Pair with osint_navigator_query for natural-language follow-ups.", input: "{ query: string, category?: string, limit?: number }" },
     { name: "oathnet_lookup", description: "Corroborating leaked-data + identity source. v2 breach search for email/username/phone/domain; geo+ASN for ip. 100 calls/day.", when_to_use: "Fire ONCE per high-value email/username/phone/domain in parallel with the other breach sources; once per newly-confirmed email/handle mid-run; on every ip seed (geo+ASN).", input: "{ kind, value }" },
    { name: "synapsint_lookup", description: "Synapsint multi-endpoint aggregator. Endpoints: links/subdomains/dns/waf/tenant/leaks/whoisd/dmarc/sh/tls/ranking/pastes/dnssec (domain); check/rip/whoiss (ip); asn; email; cve. Free-tier quota.", when_to_use: "Secondary corroboration for domain/ip/email/cve/asn seeds. Especially useful for rip (shared-hosting neighbors), tenant (M365), pastes, and domain-wide leaks that other tools don't cover.", input: "{ endpoint, value }" },
    { name: "socialfetch_lookup", description: "PRIMARY profile fetch for tiktok/instagram/twitter/facebook handles (10k credit pool — use aggressively).", when_to_use: "FIRST choice on any handle confirmed for tiktok/instagram/twitter/facebook. Fan out across all four platforms in parallel on every newly discovered handle. Profile bios contain links, names, and locations that drive the next pivot. Fall back to jina_reader_scrape if SocialFetch errors.", input: "{ platform, username }" },
    { name: "cordcat_discord_lookup", description: "CordCat Discord OSINT — given a 17-20 digit Discord snowflake ID, returns Discord profile (username, global_name, avatar, banner, public_flags), breach hits, FiveM records, and DSA sanction statements.", when_to_use: "Every Discord snowflake ID surfaced as a seed or pivot. The Discord username alone is NOT enough — extract the numeric ID first (e.g. via jina_reader_scrape on a Discord profile/invite page). 60 req/hour budget.", input: "{ discord_id: string }" },
    { name: "jina_reader_scrape", description: "ONLY single-page scraper. Free Jina Reader returns clean LLM-ready markdown for any public URL.", when_to_use: "Default for ANY scrape/extract-content task: profile pages, articles, forums, leak listings, dorks hits, Discord/Telegram web links, anything where you want the page body. Free — fire liberally.", input: "{ url, maxChars? }" },
    { name: "exa_search", description: "Exa neural+keyword search with optional inline contents. Categories: company, research paper, news, pdf, github, tweet, personal site, linkedin profile, financial report. Date-bounded via startPublishedDate/endPublishedDate.", when_to_use: "PRIMARY web search alongside minimax_web_search — run BOTH in parallel. Best for: semantic person/company discovery (neural mode), linkedin/personal-site/research-paper category-filtered queries, and any time-bounded news/research sweep.", input: "{ query, type?, numResults?, includeDomains?, excludeDomains?, startPublishedDate?, endPublishedDate?, category?, contents? }" },
    { name: "exa_find_similar", description: "Exa findSimilar — given a known URL, return semantically similar pages.", when_to_use: "After confirming any single profile URL (linkedin profile, personal site, github, twitter) — use to find the same person's other profiles or related entities. Powerful identity-pivot tool.", input: "{ url, numResults?, excludeSourceDomain?, contents? }" },
    { name: "exa_get_contents", description: "Exa /contents — fetch full text + AI summary + highlights for up to 10 URLs in one call. Best for bulk URL reading.", when_to_use: "When you have several URLs from exa_search / dorks and want their text in one batch instead of N jina_reader_scrape calls. Set livecrawl='always' for breaking news or pages you suspect Exa has cached stale.", input: "{ urls: string[], livecrawl?, text?, highlights?, summary?, maxCharacters? }" },
    { name: "ip_intel",       description: "IP geolocation, ASN, hosting info.", when_to_use: "Every ip seed and every IP discovered from DNS.", input: "{ ip: string }" },
    { name: "shodan_internetdb", description: "Open ports, vulns, cert subjects for an IP/domain via Shodan InternetDB.", when_to_use: "ip seeds and on resolved IPs of domain seeds.", input: "{ value }" },
    { name: "whois_lookup",   description: "RDAP/WHOIS registrant data for a domain.", when_to_use: "Every domain seed. Pivot on registrant email/name.", input: "{ domain }" },
    { name: "dns_records",    description: "A/AAAA/MX/NS/TXT records for a domain.", when_to_use: "Every domain seed. Pivot on returned IPs and MX hostnames.", input: "{ domain }" },
    { name: "crtsh_subdomains", description: "Certificate-transparency subdomain discovery.", when_to_use: "Every domain seed. Each subdomain → http_fingerprint.", input: "{ domain }" },
    { name: "hackertarget",   description: "Reverse-IP and hostsearch via hackertarget.com.", when_to_use: "domain (hostsearch) and ip (reverseiplookup) seeds.", input: "{ kind, value }" },
    { name: "username_sweep", description: "Built-in Username Sweep: parallel HTTP existence check across ~95 platforms for a handle. Edge-native. Only call this on a handle with NO spaces. Do NOT call it on a full name or name+location seed — derive candidate handles first.", when_to_use: "Every username/handle. Results are [VERIFY] — never confirmed alone.", input: "{ username }" },
    { name: "username_search", description: "Alias of username_sweep (same built-in ~95-site existence check). Same no-spaces rule applies.", when_to_use: "When you want a narrower confirmation than username_sweep.", input: "{ username, platforms? }" },
    { name: "github_user",    description: "GitHub profile, public emails, repos, bio.", when_to_use: "Every username seed and on github.com hits from sweep.", input: "{ username }" },
    { name: "github_code_search", description: "Search public GitHub code for a string.", when_to_use: "Stage 2 (gated): non-consumer domain only. Find leaks/configs that mention the seed.", input: "{ query }" },
    { name: "hunter_domain_search", description: "Hunter.io domain search — emails associated with a domain plus department/seniority/sources.", when_to_use: "Every non-consumer domain seed and every domain pivoted from an email. Cheap and high-signal.", input: "{ domain, limit?, department?, seniority? }" },
    { name: "hunter_email_finder", description: "Hunter.io email finder — guess + verify an email from a person's name and a domain.", when_to_use: "When you have a name + corporate domain pair and want a likely email.", input: "{ domain, first_name?, last_name?, full_name? }" },
    { name: "hunter_email_verifier", description: "Hunter.io deliverability + risk verification for an email address.", when_to_use: "Run on any new high-value email to grade confidence (deliverable / risky / undeliverable, MX, SMTP, disposable, webmail).", input: "{ email }" },
    { name: "hunter_combined", description: "Hunter.io combined person + company enrichment for an email.", when_to_use: "Run on every confirmed email — returns name, role, social links, company info, employee count, tech stack.", input: "{ email }" },
    { name: "archive_url", description: "Submit a URL to the Wayback Machine to create a permanent archived snapshot (chain of custody).", when_to_use: "After confirming any evidence URL that may disappear (social posts, leak listings, scam sites). Required for [CONFIRMED] findings on volatile sources.", input: "{ url }" },
    { name: "hackernews_user",description: "Hacker News profile + recent comments.", when_to_use: "Every username seed.", input: "{ username }" },
    { name: "reddit_user",    description: "Reddit profile + recent activity.", when_to_use: "Every username seed.", input: "{ username }" },
    { name: "wayback_snapshots", description: "Wayback Machine snapshot index for a URL.", when_to_use: "url seeds. Extract old emails/handles from snapshots.", input: "{ url }" },
    { name: "http_fingerprint", description: "Live HTTP fetch + headers + title + meta.", when_to_use: "url and subdomain seeds. Feed the body to minimax_extract.", input: "{ url }" },
    { name: "crypto_wallet",  description: "Chain lookup — balance, tx count, related addresses.", when_to_use: "crypto seeds and any wallet address discovered.", input: "{ chain, address }" },
    { name: "google_dorks",   description: "Pre-built Google dork queries.", when_to_use: "Stage 2 (gated): requires a known name or username artifact.", input: "{ target, kind? }" },
    { name: "dork_harvest",   description: "Run the document/leak dorks and AUTO-RECORD any PDFs/Office docs/CSVs/SQL/log/env files + pastebin URLs as artifacts (kind='document' or 'leak_paste').", when_to_use: "Right after google_dorks on every seed, and again on every newly-discovered email/handle/domain/name/wallet. This is how dorks become real evidence — google_dorks alone only emits URLs to click.", input: "{ seed, kind, max_queries? }" },
     { name: "gemini_deep_dork", description: "DEEP dork via Gemini 2.5 Flash with native Google Search grounding. Gemini drafts 5-8 targeted dorks, runs them on real Google, and returns a synthesized writeup + every cited URL (auto-recorded as artifacts). ~$0.002/call.", when_to_use: "Fire on EVERY email, username, name, domain, and crypto_wallet seed (and on every newly-confirmed high-value email/handle/name/domain mid-run). Run in parallel with dork_harvest — they complement, not replace each other. Use focus= to target leak sites, niche forums, paste sites, etc.", input: "{ seed, kind, focus? }" },
    { name: "urlscan_search", description: "URLScan.io historical scans for domain/ip/url.", when_to_use: "Stage 2 (gated). Every domain/ip/url seed.", input: "{ query }" },
    { name: "minimax_web_search", description: "Live web search with citations powered by Perplexity Sonar. Performs real-time grounded search and returns a synthesized answer plus cited URLs.", when_to_use: "Stage 2 gated search. Use for quick live web pivots on seeds, emails, handles, names, domains, and URLs before deeper analysis.", input: "{ query, focus? }" },
    { name: "minimax_extract", description: "Extract structured entities (emails/handles/phones/urls/ips/names/etc) from any blob of raw text.", when_to_use: "MANDATORY after any tool returning >500 chars of free-form text. Not rate-limited.", input: "{ text, context? }" },
    { name: "minimax_correlate", description: "Cluster, dedup, rescore confidence, flag contradictions across artifacts.", when_to_use: "End of fan-out round OR after ≥3 new artifacts. Smart-tier model.", input: "{ seed, artifacts[] }" },
    { name: "minimax_plan_pivots", description: "Plan the next batch of tool calls based on what's been found.", when_to_use: "Once per fan-out round, at the end. Smart-tier model.", input: "{ seed, already_queried[], artifacts[], budget_remaining }" },
    { name: "record_artifacts", description: "Bulk-insert artifacts. THE primary recording call.", when_to_use: "Once per assistant turn with an array of every artifact found this round.", input: "{ artifacts: [{ kind, value, confidence?, source?, metadata? }] }" },
    { name: "record_artifact", description: "Backwards-compatible single-item shim. PREFER record_artifacts.", when_to_use: "Avoid. Use record_artifacts instead.", input: "{ kind, value, confidence?, source?, metadata? }" },
    { name: "record_evidence", description: "Append a tamper-evident chain-of-custody row for a single high-stakes finding (hash-chained, append-only, auditable).", when_to_use: "Any Hard-classified claim, official record, archived URL, or verified breach hit — alongside record_artifacts.", input: "{ classification: 'hard'|'soft', kind, value, source, source_url?, confidence?, notes?, metadata? }" },
    { name: "memory_recall", description: "Recall prior cross-investigation memory (patterns, connections, lessons, identity clusters) for a value. Free.", when_to_use: "FIRST turn on the seed; again on every newly confirmed high-value artifact before spending fresh quota.", input: "{ subject: string, kind?: 'pattern'|'connection'|'lesson'|'identity'|'any', limit?: number }" },
    { name: "memory_save", description: "Persist durable cross-investigation memory (batch). Free.", when_to_use: "ONCE at the end of the investigation with every connection/pattern/lesson worth keeping.", input: "{ entries: [{ kind, subject, subject_kind?, related_values?, content, confidence? }] }" },
    { name: "list_tools",     description: "Returns this catalog. Cached per investigation — do not call more than once.", when_to_use: "First turn only, if you need the catalog. Never again.", input: "{}" },
    { name: "deepfind_reverse_email", description: "DeepFind.Me reverse-email account discovery across ~120 services (shared DeepFind 1000/day budget).", when_to_use: "Every confirmed email — finds where the email is registered. High-signal for identity correlation.", input: "{ email }" },
    { name: "deepfind_disposable_email", description: "DeepFind.Me burner/temp email detector.", when_to_use: "Grade every new email's credibility before pivoting on it.", input: "{ email }" },
    { name: "deepfind_ransomware_exposure", description: "DeepFind.Me ransomware leak-site exposure check.", when_to_use: "Every non-consumer domain seed and every corporate email — surfaces breach/extortion context.", input: "{ query }" },
    { name: "deepfind_ssl_inspect", description: "DeepFind.Me SSL/TLS certificate inspector (issuer, SANs, validity, misconfig warnings).", when_to_use: "Every domain seed — SANs often expose related hostnames worth pivoting on.", input: "{ domain }" },
    { name: "deepfind_tech_stack", description: "DeepFind.Me tech-stack detector (CMS, frameworks, analytics, CDN).", when_to_use: "Every url/domain seed — correlate analytics IDs across sites later.", input: "{ url }" },
    { name: "deepfind_url_unshorten", description: "DeepFind.Me URL unshortener — full redirect chain + safety signal.", when_to_use: "Every short-link discovered (bit.ly, t.co, lnkd.in, ow.ly, etc).", input: "{ url }" },
    { name: "deepfind_profile_analyzer", description: "DeepFind.Me deep username sweep across ~350 sites (vs local sweep's ~95). Slow.", when_to_use: "High-value handles only, or when the local username_sweep returned thin coverage. Burns budget — do not spam.", input: "{ username }" },
    { name: "deepfind_telegram_channel", description: "DeepFind.Me Telegram channel metadata + recent messages.", when_to_use: "When a Telegram handle/link is discovered.", input: "{ handle }" },
    { name: "deepfind_telegram_search", description: "DeepFind.Me Telegram channel keyword search.", when_to_use: "When investigating a topic/community and you need to find related channels.", input: "{ query }" },
    { name: "deepfind_vin_lookup", description: "DeepFind.Me VIN decoder (NHTSA vPIC + safety recalls).", when_to_use: "Any 17-char VIN artifact discovered.", input: "{ vin }" },
    { name: "deepfind_aircraft_lookup", description: "DeepFind.Me FAA N-Number lookup (US-registered aircraft → owner of record).", when_to_use: "Any N-Number tail code (e.g. N737AS) discovered.", input: "{ nNumber }" },
    { name: "deepfind_vessel_lookup", description: "DeepFind.Me vessel lookup (IMO / MMSI → vessel + ownership).", when_to_use: "Any IMO or MMSI discovered.", input: "{ identifier }" },
    { name: "deepfind_mac_lookup", description: "DeepFind.Me MAC address → vendor lookup.", when_to_use: "Any MAC address discovered in logs/EXIF/etc.", input: "{ macAddress }" },
    { name: "deepfind_dark_web_link", description: "DeepFind.Me .onion validator + 18k+ service DB check.", when_to_use: "Any .onion URL discovered.", input: "{ url }" },
    { name: "virustotal_lookup", description: "VirusTotal v3 reputation/detection lookup for file hash, URL, domain, or IP. Public quota: 4/min, 500/day.", when_to_use: "High-value artifacts only — suspicious domains/IPs/URLs surfaced by other tools, or any file hash. Do NOT call on every artifact; reserve for ones already flagged risky.", input: "{ kind:'file'|'url'|'domain'|'ip', value }" },
    { name: "ipgeolocation_lookup", description: "IPGeolocation.io secondary IP enrichment — geo, ISP, ASN, connection type, currency, timezone. 1000/day.", when_to_use: "Every ip seed AFTER ip_intel — corroborate or contradict to flag VPN/proxy/mobile.", input: "{ ip }" },
  ],
  fan_outs: {
    email:    ["triage_seed (MANDATORY first — fires breach_check via stolen.tax)", "Cheap parallel: hunter_email_verifier, hunter_combined (if HUNTER_API_KEY set), leakcheck_lookup (200/day), oathnet_lookup (100/day, parallel — not fallback), bosint_email_lookup (1000/day shared), deepfind_disposable_email (credibility grade), deepfind_reverse_email (account discovery across ~120 services)", "→ then Stage 2 if cleared: github_code_search, google_dorks + dork_harvest + gemini_deep_dork (run all three in parallel), minimax_web_search, urlscan_search. NOTE: intelbase_email_lookup is PERMANENTLY DISABLED — do not request it."],
    username: ["triage_seed (MANDATORY first)", "Always parallel (not gated): username_sweep, github_user, hackernews_user, reddit_user, oathnet_lookup", "Stage 2 if cleared: same set as email — including gemini_deep_dork on the handle"],
    phone:    ["bosint_phone_lookup (carrier + line type + location — primary phone enrichment, 1000/day shared)", "leakcheck_lookup (phone breach search, 200/day)", "oathnet_lookup (phone breach search, 100/day — call in parallel)", "google_dorks", "dork_harvest", "gemini_deep_dork", "minimax_web_search"],
    ip:       ["ip_intel", "ipgeolocation_lookup (corroborate geo + connection type — flag VPN/proxy on disagreement)", "shodan_internetdb", "hackertarget(reverseiplookup)", "urlscan_search(ip:)", "oathnet_lookup (geo+ASN, not breach — OK to call)", "virustotal_lookup(kind:'ip') ONLY if the IP looks suspicious (shodan vulns, hosting flag, urlscan hits)"],
    domain:   ["whois_lookup", "dns_records", "crtsh_subdomains", "hackertarget(hostsearch)", "urlscan_search(domain:)", "http_fingerprint",  "hunter_domain_search", "deepfind_ssl_inspect (SANs → more hostnames)", "deepfind_tech_stack", "deepfind_ransomware_exposure (corporate domains)", "virustotal_lookup(kind:'domain') ONLY for suspicious/newly-registered/typosquat domains"],
    subdomain:["http_fingerprint", "dns_records", "(pivot on A record → ip fan-out)"],
    url:      [
      "IF host is instagram.com / tiktok.com / x.com / twitter.com / facebook.com: extract the @handle from the path, strip tracking params (?igsh=, ?s=, ?utm_*), and run socialfetch_lookup FIRST (before http_fingerprint, jina_reader_scrape, or username_sweep). SocialFetch is the primary social profile reader — fan out across all four platforms in parallel on the extracted handle.",
      "http_fingerprint",
      "wayback_snapshots",
      "archive_url (preserve evidence)",
      "deepfind_url_unshorten (if shortener)",
      "deepfind_tech_stack",
      "virustotal_lookup(kind:'url') ONLY for phishing/scam suspects",
      "(extract emails/handles → pivot)",
    ],
    name:     ["google_dorks(name)", "dork_harvest(name)", "gemini_deep_dork(name, focus='disambiguate person + location + employer')", "(cross-reference against found socials)"],
    "name+location": ["for name+location searches, keep Candidate Identity Clusters separate; never collapse into a single identity"],
    person:   [
      "minimax_web_search(name + location) — primary discovery for person seeds",
      "google_dorks(name)",
      "derive candidate handles (firstlast, first.last, flast) BEFORE any username_sweep call",
      "record candidate identities as SEPARATE clusters",
      "do NOT run username_sweep on the full name/location string — it has spaces and will fail/get skipped",
      "if same-name out-of-area results appear, mark as possible same-name collision and keep in own cluster",
    ],
    crypto:   ["crypto_wallet"],
    breach:   ["record the breach", "(pivot on any leaked passwords/usernames/emails inside)"],
  },
  notes:
    "Tag every finding row with EXACTLY ONE label. [CONFIRMED] = direct profile/source fact OR corroborated by 2+ independent source classes. [INFERRED] = correlated but not definitive. [VERIFY] = needs human check; username_sweep hits and breach-only sensitive identity attributes (DOB, phone, address, full name, SSN) belong here unless corroborated. [FAILED] = tool error / no data. [LOW] = single weak source or possible same-name collision. (Extended labels [CORRELATED] and [CONFLICT] are also supported by the UI parser — see FINDING_LABELS.) For person/name/location seeds, the final report MUST include a Candidate Identity Clusters section whenever multiple same-name candidates appear. Example row: | [CONFIRMED] | `alice@example.com` | breach_check + github_user (2 source classes) | 90% |",
};

// Per-investigation memo so list_tools is effectively free after the first call.
export const CATALOG_CACHE = new Map<string, typeof TOOL_CATALOG>();

// Inline label rule — short enough to keep in the system prompt because the UI
// parser depends on it. Detailed examples live in TOOL_CATALOG.notes.
export const FINDING_LABELS = `
## Finding labels (REQUIRED — UI parser depends on this)
Tag every Findings row with EXACTLY ONE: [CONFIRMED] | [CORRELATED] | [INFERRED] | [VERIFY] | [CONFLICT] | [FAILED] | [LOW].
- CONFIRMED = supported by ≥2 INDEPENDENT source classes (e.g. live profile + WHOIS, or hunter + GitHub), OR a direct first-party source page. Breach data is ONE source class — breach + leak ≠ two classes.
- CORRELATED = multiple artifacts point together but no definitive proof.
- INFERRED = single source states this, not independently corroborated. Default for single-tool hits.
- VERIFY = possible match; needs verification before reporting. username_sweep hits start here unless corroborated.
- CONFLICT = artifact conflicts with the seed (e.g. seed location vs IP geo, different state, different area code) or with another cluster's strong identifier. Use this aggressively to prevent merging two same-name people.
- LOW = weak lead.
- FAILED = false positive or tool failure.

Sensitive PII (DOB, address, phone, SSN, full name) MUST NOT be tagged CONFIRMED on breach-only evidence — cap at INFERRED until a non-breach source corroborates.`;
