#!/usr/bin/env node
/**
 * stamp-build.mjs — write the current git commit into the osint-agent build
 * marker so the deployed edge function's /health endpoint is verifiable against
 * source (deploy-drift detection).
 *
 * The osint-agent function is deployed by Lovable from the mirror repo
 * (seeker-spark-search-5362c57c), NOT by `supabase functions deploy`. Lovable's
 * pipeline does not run npm scripts for edge functions, so the marker has to be
 * a COMMITTED generated file — this script regenerates it on demand.
 *
 * Run it as the last step before syncing osint-agent to the mirror for a
 * redeploy:  npm run stamp:build  →  commit  →  sync to mirror  →  Lovable deploys
 *  →  curl .../osint-agent?health=1  →  confirm `build` == the short SHA you shipped.
 *
 * Note the one-commit offset: the marker holds HEAD *at stamp time*, so after you
 * commit the stamped file the marker names that commit's parent. That is still
 * sufficient for drift detection — compare the live `build` SHA against recent
 * `git log` and confirm it is the latest deployed commit (not a weeks-old build).
 */
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "supabase", "functions", "osint-agent", "build-info.ts");

const sha = execSync("git rev-parse --short HEAD", { encoding: "utf8" }).trim();
const committedAt = execSync("git log -1 --format=%cI", { encoding: "utf8" }).trim();

const contents = `// AUTO-GENERATED by scripts/stamp-build.mjs — do not edit by hand.
// Holds the git commit this osint-agent build was stamped from, surfaced at
// /health (\`build\`) so a deployed function can be checked against source.
export const BUILD_MARKER = "${sha}";
export const BUILD_COMMITTED_AT = "${committedAt}";
`;

writeFileSync(out, contents);
console.log(`stamped build marker: ${sha} (commit ${committedAt}) -> ${out}`);
