// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Use to verify connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/list-investigations.ts
import { createClient } from "npm:@supabase/supabase-js@^2.106.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_investigations_default = defineTool2({
  name: "list_investigations",
  title: "List investigations",
  description: "List the signed-in analyst's Swarmbot OSINT investigation threads, most recently updated first.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).default(20).describe("Max threads to return.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client(ctx).from("threads").select("id,title,seed_type,seed_value,status,credits_used,created_at,updated_at").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { investigations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-investigation.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.106.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_investigation_default = defineTool3({
  name: "get_investigation",
  title: "Get investigation",
  description: "Fetch a single Swarmbot investigation thread with its messages and artifacts for the signed-in analyst.",
  inputSchema: {
    thread_id: z3.string().uuid().describe("Investigation thread UUID."),
    message_limit: z3.number().int().min(1).max(200).default(50),
    artifact_limit: z3.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ thread_id, message_limit, artifact_limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = client2(ctx);
    const [thread, messages, artifacts] = await Promise.all([
      sb.from("threads").select("*").eq("id", thread_id).eq("user_id", ctx.getUserId()).maybeSingle(),
      sb.from("messages").select("*").eq("thread_id", thread_id).order("created_at", { ascending: true }).limit(message_limit),
      sb.from("artifacts").select("*").eq("thread_id", thread_id).order("created_at", { ascending: false }).limit(artifact_limit)
    ]);
    if (thread.error) return { content: [{ type: "text", text: thread.error.message }], isError: true };
    if (!thread.data) return { content: [{ type: "text", text: "Investigation not found" }], isError: true };
    const payload = { thread: thread.data, messages: messages.data ?? [], artifacts: artifacts.data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "skzqwbyvmwqarfgfvyky";
var mcp_default = defineMcp({
  name: "swarmbot-mcp",
  title: "Swarmbot OSINT",
  version: "0.1.0",
  instructions: "Tools for the Swarmbot OSINT investigator. Use `echo` to verify connectivity, `list_investigations` to see the analyst's recent investigation threads, and `get_investigation` to pull a full thread with its messages and artifacts.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [echo_default, list_investigations_default, get_investigation_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
