// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Public Supabase frontend credentials. The anon/publishable key is designed to
// ship in the client bundle (security is enforced by Row Level Security), so these
// are safe to bake in as defaults — the app boots without per-environment .env
// wiring. Override either value with VITE_SUPABASE_* env vars when needed.
const DEFAULT_SUPABASE_URL = "https://skzqwbyvmwqarfgfvyky.supabase.co";
const DEFAULT_SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrenF3Ynl2bXdxYXJmZ2Z2eWt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk3ODg5MTksImV4cCI6MjA5NTM2NDkxOX0.B2k5sI10zk1nxjZdXEFxuVV3B755FxDFGkT6TfWY6TE";

const SUPABASE_URL =
  (import.meta.env.VITE_SUPABASE_URL as string | undefined)?.trim() || DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined)?.trim() ||
  DEFAULT_SUPABASE_PUBLISHABLE_KEY;

export const hasSupabaseEnv = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
export const supabaseConfigError = hasSupabaseEnv
  ? null
  : 'Missing VITE_SUPABASE_URL and/or VITE_SUPABASE_PUBLISHABLE_KEY. Copy .env.example to .env and set your Supabase frontend values.';

function createMissingSupabaseProxy(path: string[] = []): unknown {
  const fail = () => {
    throw new Error(`${supabaseConfigError} (attempted supabase.${path.join('.') || '<root>'})`);
  };

  return new Proxy(fail, {
    get(_target, prop) {
      if (prop === 'then') return undefined;
      return createMissingSupabaseProxy([...path, String(prop)]);
    },
    apply() {
      fail();
    },
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = hasSupabaseEnv
  ? createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : createMissingSupabaseProxy() as ReturnType<typeof createClient<Database>>;